CONTRIBUTING.md
README.md
packages/docs/PAGES.md
packages/docs/pages/Badge/BadgePage.tsx
packages/docs/pages/Button/ButtonPage.tsx
packages/docs/pages/Checkbox/CheckboxPage.tsx
packages/docs/pages/Dropdown/DropdownPage.tsx
packages/docs/pages/Form/FormPage.tsx
packages/docs/pages/GettingStarted/GettingStartedPage.tsx
packages/docs/pages/Grid/GridPage.tsx
packages/docs/pages/Icons/IconsPage.tsx
packages/docs/pages/Input/InputPage.tsx
packages/docs/pages/Link/LinkPage.tsx
packages/docs/pages/Radio/RadioPage.tsx
packages/docs/pages/Select/SelectPage.tsx
packages/docs/pages/Textarea/TextareaPage.tsx
packages/docs/pages/Tooltip/TooltipPage.tsx

Changes @amckemie requested, plus some url updates.

chore(docs): add and update links to docs

---

README.md
packages/big-design-icons/README.md
packages/big-design-theme/README.md
packages/big-design/README.md

chore: add README badges

---

packages/big-design-icons/README.md
packages/big-design-theme/README.md

Fix 2 URLs in READ.me to point to correct dev docs site

chore(docs): update docs urls

---

packages/big-design/src/components/Select/Select.tsx
packages/big-design/src/components/Select/spec.tsx

Component will now match the input text to the value selected, without having to click an option.

fix(component): select will now change input text if value changes

---

packages/docs/components/SideNav/SideNav.tsx
packages/docs/components/SideNav/SideNavLogo/SideNavLogo.tsx
packages/docs/components/SideNav/SideNavMenu/styled.tsx
packages/docs/components/SideNav/styled.tsx
packages/docs/pages/_app.tsx

@deini mentioned some changes, so refactored it.

refactor(component): updated code structure from PR #165

---

packages/big-design/src/components/Modal/Modal.tsx
packages/big-design/src/components/Modal/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Modal/spec.tsx

Prevent scrolling on open modals.
Could be BREAKING CHANGE, so let me know if I need to amend the commit.

fix(component): added scroll prevention on open modals

---

packages/big-design/src/components/Modal/Modal.tsx
packages/big-design/src/components/Modal/spec.tsx

`<Modal isOpen={true} ...` now renders appropriately

fix(component): allow modal to be open on initial render

---

packages/big-design/src/components/Badge/Badge.tsx
packages/big-design/src/components/Checkbox/Checkbox.tsx
packages/big-design/src/components/Form/Fieldset/Fieldset.tsx
packages/big-design/src/components/Link/Link.tsx
packages/big-design/src/components/List/Item/Item.tsx
packages/big-design/src/components/Radio/Radio.tsx
packages/big-design/src/components/Typography/Typography.tsx

Noticed certain components were getting re-rendered. This is an attempt to gain a little performance boost.

feat(component): add memoization to certain components

---

packages/big-design/src/components/Badge/Badge.tsx
packages/big-design/src/components/Badge/spec.tsx
packages/big-design/src/components/Box/Box.tsx
packages/big-design/src/components/Box/spec.tsx
packages/big-design/src/components/Button/spec.tsx
packages/big-design/src/components/Checkbox/Checkbox.tsx
packages/big-design/src/components/Checkbox/spec.tsx
packages/big-design/src/components/Checkbox/styled.tsx
packages/big-design/src/components/Chip/Chip.tsx
packages/big-design/src/components/Chip/spec.tsx
packages/big-design/src/components/Typography/Typography.tsx

Partial implementation of https://github.com/bigcommerce/big-design/issues/190
Covers:
- Badge
- Box
- Button
- Checkbox
- Chip
- Typography

fix(component): forward theme prop

---

packages/docs/utils/analytics/gtm.ts

Updating GTM tag to new version.

fix: update GTM tag to new version

---

packages/big-design-icons/scripts/downloader.js

Material icons changed their API url + response. This PR updates the downloader to use the new structure.

fix(icons): use new api on icon downloader

---

packages/big-design-icons/src/components/RemoveIcon.tsx
packages/big-design-icons/src/components/index.ts
packages/big-design-icons/svgs/material/remove.svg
packages/big-design/src/components/Checkbox/Checkbox.tsx
packages/big-design/src/components/Checkbox/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Checkbox/spec.tsx
packages/big-design/src/components/Checkbox/styled.tsx
packages/docs/PropTables/CheckboxPropTable.tsx
packages/docs/pages/Checkbox/CheckboxPage.tsx

Add indeterminate state to checkboxes.

feat(component): add indeterminate state to checkboxes

---

packages/docs/pages/Pagination/PaginationPage.tsx

Fixes pagination example items calculation + infinite loop case.

fix(docs): fix pagination docs example

---

packages/big-design/src/components/Chip/styled.tsx
packages/big-design/src/components/Dropdown/Dropdown.tsx
packages/big-design/src/components/Flex/Flex.tsx
packages/big-design/src/components/Flex/Item/index.ts
packages/big-design/src/components/Grid/Grid.tsx
packages/big-design/src/components/Grid/Item/index.ts
packages/big-design/src/components/List/Action/index.ts
packages/big-design/src/components/List/Item/index.ts
packages/big-design/src/components/List/index.ts
packages/big-design/src/components/Modal/Modal.tsx
packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Select/Select.tsx

Cleaned up imports/exports for consistency.

style: rework exports and imports on components

---

packages/big-design/src/components/Form/Label/Label.tsx
packages/big-design/src/components/Form/Label/spec.tsx
packages/big-design/src/components/Form/Label/styled.tsx
packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Input/Input.tsx
packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Input/spec.tsx
packages/big-design/src/components/Select/Select.tsx
packages/big-design/src/components/Select/spec.tsx

Appends `(optional)` to non required inputs and selects.

feat(component): add optional text to non required inputs

---

packages/docs/components/PropTable/PropTable.tsx

fix(docs): remove 'test' label from prop tables

---

packages/big-design/src/components/Panel/Panel.tsx
packages/big-design/src/components/Panel/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Panel/spec.tsx
packages/big-design/src/components/Panel/styled.tsx
packages/docs/PropTables/PanelPropTable.tsx
packages/docs/pages/Panel/PanelPage.tsx

`<Panel>` now accepts a `header` and `action` prop.

Panel API update

---

packages/big-design/src/components/Tabs/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Tabs/spec.tsx

Add missing tests for `Tabs` component.

test(component): add tests for Tabs component

---

packages/big-design/src/components/Button/Button.tsx

Convert Button component to a React Functional Component

refactor(component): convert Button component to FC

---

packages/big-design/setupTests.ts
packages/big-design/src/components/Table/Actions/Actions.tsx
packages/big-design/src/components/Table/Row/Row.tsx
packages/big-design/src/components/Table/Row/styled.tsx
packages/big-design/src/components/Table/Table.tsx
packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
packages/big-design/src/utils/index.ts
packages/big-design/src/utils/typedMemo.ts
packages/big-design/src/utils/useEventCallback.ts

refactor(component): table optimizations

---

packages/big-design/src/components/Input/styled.tsx
packages/big-design/src/components/Modal/styled.tsx
packages/docs/components/SideNav/SideNavMenu/styled.tsx
yarn.lock

`@types/styled-components` are now compatible with TS 3.7.

chore(all): bump styled-components types definition

---

.gitignore
packages/docs/next.config.js
packages/docs/pages/_app.tsx

Adds a `/dev` page to render components in isolation on dev mode.

chore(docs): add Dev Page

---

packages/big-design/src/components/Form/Error/Error.tsx
packages/big-design/src/components/Typography/Typography.tsx
packages/big-design/src/components/Typography/index.ts
packages/big-design/src/components/Typography/spec.tsx
packages/big-design/src/components/Typography/styled.tsx
packages/big-design/src/components/Typography/types.ts
packages/docs/PropTables/TypographyPropTable.tsx
packages/docs/pages/Typography/TypographyPage.tsx

feat(component): add text modifiers to typography

---

packages/docs/components/NextLink/NextLink.tsx
packages/docs/components/SideNav/SideNavLink/SideNavLink.tsx

Fix the ability to open links in new tabs.

fix(docs): opening links in new tab

---

packages/docs/pages/Checkbox/CheckboxPage.tsx

fix(docs): checkbox page typo

---

packages/docs/pages/Form/FormPage.tsx

Have less `(Optional)` fields in our docs.

feat(docs): make more fields required on Form page

---

packages/big-design/src/components/Form/Form.tsx
packages/big-design/src/components/Form/Group/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Form/Group/styled.tsx
packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Form/styled.tsx
packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Textarea/__snapshots__/spec.tsx.snap
packages/docs/PropTables/FormPropTable.tsx

Add `fullWidth` prop to `Form` to allow for alternative layouts (eg: forms inside modals)

feat(component): add fullWidth prop to Form

---

packages/big-design/src/components/Table/HeaderCell/HeaderCell.tsx
packages/big-design/src/components/Table/HeaderCell/styled.tsx
packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Table/spec.tsx

Fix `align: right` on a table header.

fix(component): table header right alignment

---

packages/docs/pages/Checkbox/CheckboxPage.tsx
packages/docs/pages/Input/InputPage.tsx
packages/docs/pages/Textarea/TextareaPage.tsx

Wrap some documentation around a `Form` component to fix layout.

fix(docs): add Form component around form controls

---

packages/big-design/src/components/Table/styled.tsx

fix(component): dropdowns inside TableFigure

---

packages/big-design/package.json
yarn.lock

chore(component): remove unused dep

---

packages/big-design/src/components/Panel/Panel.tsx
packages/big-design/src/components/Panel/spec.tsx
packages/big-design/src/components/Panel/styled.tsx
packages/big-design/src/mixins/margins/index.ts
packages/big-design/src/mixins/margins/margins.tsx
packages/big-design/src/mixins/margins/spec.tsx
packages/big-design/src/mixins/paddings/index.ts
packages/big-design/src/mixins/paddings/paddings.tsx
packages/big-design/src/mixins/paddings/spec.tsx

feat(component): add exclude padding/margin props helpers
fix(component): panel now forwards data attrs

feat(component): exclude padding/margin props helpers

---

packages/big-design-theme/package.json
packages/big-design/package.json

Cap jest workers to circleci's number of CPUs.

chore(all): cap jest workers

---

commitlint.config.js

chore(all): add commitlint deps scope

---

package.json
packages/big-design/src/components/Flex/spec.tsx
packages/docs/pages/_app.tsx
yarn.lock

Bump dependencies and some minor changes needed for the new dependencies.

chore(deps): bump dependencies

---

packages/docs/pages/Modal/ModalPage.tsx

Update the modal examples to have correct button usage.

fix(docs): fix modal examples

---

packages/big-design/src/components/Dropdown/Dropdown.tsx
packages/big-design/src/components/Dropdown/spec.tsx
packages/big-design/src/components/Dropdown/types.ts
packages/big-design/src/components/List/GroupHeader/ListGroupHeader.tsx
packages/big-design/src/components/List/GroupHeader/index.ts
packages/big-design/src/components/List/GroupHeader/styled.tsx
packages/docs/PropTables/DropdownPropTable.tsx
packages/docs/pages/Dropdown/DropdownPage.tsx

Adds optional list groups and headers to dropdown component, updates tests.
Added tests for grouped dropdowns, tested with screen reader. 
See screenshot below

feat(component): Chp 5713 add list groups w/headers to Dropdown component

---

packages/big-design/src/components/Button/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Button/styled.tsx
packages/big-design/src/components/Checkbox/Checkbox.tsx
packages/big-design/src/components/Checkbox/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Checkbox/styled.tsx
packages/big-design/src/components/Chip/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Form/Label/styled.tsx
packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Input/styled.tsx
packages/big-design/src/components/Link/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Link/styled.tsx
packages/big-design/src/components/List/Item/styled.tsx
packages/big-design/src/components/Modal/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
packages/big-design/src/components/ProgressBar/__snapshots__/spec.tsx.snap
packages/big-design/src/components/ProgressBar/styled.tsx
packages/big-design/src/components/ProgressCircle/__snapshots__/spec.tsx.snap
packages/big-design/src/components/ProgressCircle/styled.tsx
packages/big-design/src/components/Radio/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Radio/styled.tsx
packages/big-design/src/components/Select/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Table/Row/styled.tsx
packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Tabs/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Textarea/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Textarea/styled.tsx
packages/big-design/src/mixins/transitions/index.ts
packages/big-design/src/mixins/transitions/transitions.tsx

Apply small transition for a smoother hover effect on inputs/buttons.
Depends on https://github.com/bigcommerce/big-design/pull/273

Add transitions to components

---

packages/examples/package.json
yarn.lock

fix(examples): pin to correct version of bd

---

packages/tests/functional/basic.ts
packages/tests/logger.js
packages/tests/package-lock.json
packages/tests/package.json
packages/tests/wdio.conf.js

Add logging for tests and actions to a file
Keeps logs in the console as well
Proof:
From file `1575414593343-Bigcommerce_page_should_have_the_right_title.log`:
```
[2019-12-03T17:09:53.348] [INFO] test - --- Starting test Bigcommerce page should have the right title ---
[2019-12-03T17:09:53.350] [INFO] test - Navigating to bigcommerce.com
[2019-12-03T17:09:57.229] [INFO] test - --- Ending test Bigcommerce page should have the right title ---
```
From console:
```
[0-0] --- Starting test Bigcommerce page should have the right title ---
[0-0] Navigating to bigcommerce.com
[0-0] --- Ending test Bigcommerce page should have the right title ---
```

QPT-11: Implement a Logger in Testing

---

packages/big-design/src/components/Checkbox/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Checkbox/spec.tsx
packages/big-design/src/components/Checkbox/styled.tsx
packages/big-design/src/components/Radio/Radio.tsx
packages/big-design/src/components/Radio/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Radio/spec.tsx
packages/big-design/src/components/Radio/styled.tsx

Fixed disabled state for `<Checkbox />` and implemented disabled state for `<Radio />`

fix(component): disabled state styles for radio and checkbox

---

packages/docs/PropTables/StatefulTablePropTable.tsx
packages/docs/PropTables/TablePropTable.tsx
packages/docs/pages/Table/TablePage.tsx

fix(docs): table sorting example + table action prop 

---

.circleci/config.yml

chore(ci): disable nextjs telemetry

---

packages/big-design/src/components/Link/Link.tsx
packages/big-design/src/components/Link/spec.tsx
packages/big-design/src/components/Link/styled.tsx
packages/docs/PropTables/LinkPropTable.tsx
packages/docs/PropTables/TypographyPropTable.tsx

feat(component): add ellipsis prop to Link

---

packages/big-design/src/components/Flex/Flex.tsx
packages/big-design/src/components/Flex/index.ts
packages/big-design/src/components/Flex/spec.tsx
packages/big-design/src/components/Pagination/Pagination.tsx
packages/big-design/src/components/Table/Actions/Actions.tsx
packages/big-design/src/components/Table/SelectAll/SelectAll.tsx
packages/big-design/src/components/Table/TablePagination/styled.tsx
packages/docs/PropTables/FlexPropTable.tsx
packages/docs/components/SideNav/SideNav.tsx
packages/docs/components/SideNav/SideNavMenu/SideNavMenu.tsx
packages/docs/components/SideNav/SideNavMenu/styled.tsx
packages/docs/components/SnippetControls/SnippetControls.tsx
packages/docs/pages/Flex/FlexPage.tsx
packages/docs/pages/GettingStarted/GettingStartedPage.tsx

- Refactor `Flex` component to be a functional component.
- Export `FlexItem` instead of it being a static member.
Part 1 of many.

refactor(component): convert Flex to FC and export FlexItem

---

packages/big-design/src/components/Grid/Grid.tsx
packages/big-design/src/components/Grid/index.ts
packages/big-design/src/components/Grid/spec.tsx
packages/docs/PropTables/GridPropTable.tsx
packages/docs/pages/Grid/GridPage.tsx
packages/docs/pages/_app.tsx

- Refactor Flex component to be a functional component.
- Export FlexItem instead of it being a static member.
P.S. git messages, made with love in Vim.

feat(component): convert Grid to FC and export GridItem

---

packages/big-design/src/components/ProgressBar/ProgressBar.tsx

Convert ProgressBar to Functional Component.
_Let's keep this up_

feat(component): convert ProgressBar to FC

---

packages/big-design/src/components/ProgressCircle/ProgressCircle.tsx

- Refactor ProgressCircle to a functional component.
_Untitled Pull Request_

feat(component): convert ProgressCircle to FC

---

packages/big-design/src/components/Modal/Modal.tsx
packages/docs/PropTables/ModalPropTable.tsx

Convert `Modal` to functional component.
_Till Hacktember Ends_

feat(component): convert Modal to FC

---

packages/big-design/src/components/Tooltip/Tooltip.tsx

Convert the Tooltip class component to a FC and remove its static members

feat(component): convert Tooltip to FC and remove static members

---

packages/big-design/package.json
packages/big-design/src/components/Dropdown/Dropdown.tsx
packages/big-design/src/components/Select/Select.tsx
yarn.lock

Bump `scroll-into-view-if-needed` library and use `auto` behavior since it's what we now need.

feat(component): bump scroll-into-view-if-needed and use auto behavior

---

packages/examples/package.json
packages/examples/src/ProductForm.tsx
packages/examples/tsconfig.json

The CodeSandbox example wasn't updated after a breaking change.
This PR updates it and adds a `ci` step so that this doesn't happen again.

fix(examples): fix usage and add ci step

---

packages/big-design/src/components/Badge/Badge.tsx
packages/big-design/src/components/Badge/spec.tsx

Ensure `Badge` label prop is of type string.

feat(component): ensure Badge label prop is of type string

---

packages/big-design/src/components/Flex/types.ts
packages/big-design/src/components/Grid/types.ts
packages/big-design/src/mixins/display/types.ts
packages/big-design/src/mixins/margins/margins.tsx
packages/big-design/src/mixins/paddings/paddings.tsx
packages/big-design/src/types/responsive.ts

Refactored responsive props to be less verbose. Tried to make the responsive props more dynamic, but it's not really possible with Typescript 😢.
Closes #132

refactor: rework responsive props

---

packages/big-design-icons/package.json
packages/big-design-theme/package.json
packages/big-design/package.json
yarn.lock

Bump dependencies + add missing ones.

chore: bump dependencies

---

yarn.lock

Update dependencies to resolve security issues.
Closes #357.
Closes #347.

fix(deps): fix deps with security issues

---

packages/big-design/src/components/Form/index.ts

Was removed by mistake in a previous PR.

fix(component): expose FormProps

---

packages/big-design/package.json
packages/big-design/src/components/List/styled.tsx
packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
yarn.lock

Change scroll behavior to `auto`. Bump `downshift` to include latest a11y behavior update.

fix(component): change scroll behavior to auto

---

packages/big-design/src/components/Box/Box.tsx
packages/big-design/src/components/Box/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Box/spec.tsx
packages/big-design/src/components/Box/styled.tsx
packages/docs/PropTables/BoxPropTable.tsx

Adds `clearfix` prop to clearfix floated elements.

feat(component): add clearfix prop for Box component

---

.circleci/config.yml

fix(ci): bump cache version

---

packages/big-design/src/components/Select/Select.tsx
packages/big-design/src/components/Select/spec.tsx

Reduces initial re-renders of the component
Before   <img width="201" alt="Screen Shot 2020-04-29 at 9 44 59 AM" src="https://user-images.githubusercontent.com/37593557/80613707-3d86c980-8a03-11ea-8bb6-01fad3599c6e.png">  After    <img width="186" alt="Screen Shot 2020-04-29 at 9 46 10 AM" src="https://user-images.githubusercontent.com/37593557/80613720-42e41400-8a03-11ea-9649-d43be6452cb4.png">
Local, React Profiler

fix(component): improves Select component performance

---

packages/big-design/src/components/Dropdown/Dropdown.tsx
packages/big-design/src/components/Dropdown/spec.tsx
packages/big-design/src/components/Dropdown/styled.ts
packages/big-design/src/components/List/List.tsx
packages/big-design/src/components/List/styled.tsx
packages/big-design/src/components/MultiSelect/MultiSelect.tsx
packages/big-design/src/components/MultiSelect/spec.tsx
packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Select/Select.tsx
packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap

Reduces initial re-renders of components. First steps in fixing performance issues.

fix(component): improve Dropdown & MultiSelect component performance

---

packages/docs/package.json
yarn.lock

🔥 fast refresh
https://nextjs.org/blog/next-9-4#fast-refresh

chore: bump next for fast refresh

---

packages/docs/PropTables/DropdownPropTable.tsx
packages/docs/PropTables/ModalPropTable.tsx
packages/docs/components/NextLink/NextLink.tsx
packages/docs/pages/Display/DisplayPage.tsx
packages/docs/pages/Dropdown/DropdownPage.tsx
packages/docs/pages/Margin/MarginPage.tsx
packages/docs/pages/Padding/PaddingPage.tsx
packages/docs/pages/StatefulTable/StatefulTablePage.tsx

Fixes incorrect URLs and broken links in prod.

fix(docs): update broken links

---

packages/big-design/src/components/MultiSelect/MultiSelect.tsx
packages/big-design/src/components/MultiSelect/spec.tsx
packages/big-design/src/components/MultiSelect/types.ts
packages/big-design/src/components/Select/Select.tsx
packages/big-design/src/components/Select/spec.tsx
packages/big-design/src/components/Select/types.ts
packages/docs/PropTables/MultiSelectPropTable.tsx
packages/docs/PropTables/SelectPropTable.tsx

feat(component): allow FormControlLabels in Selects

---

packages/big-design/src/components/Dropdown/Dropdown.tsx
packages/big-design/src/components/MultiSelect/MultiSelect.tsx
packages/big-design/src/components/Select/Select.tsx

feat(component): set offset to 4px for dropdowns

---

packages/big-design/src/components/List/Item/Item.tsx
packages/big-design/src/components/List/Item/styled.tsx
packages/big-design/src/components/MultiSelect/MultiSelect.tsx
packages/big-design/src/components/MultiSelect/types.ts
packages/big-design/src/components/Select/Select.tsx
packages/big-design/src/components/Select/types.ts
packages/big-design/src/components/Timepicker/Timepicker.tsx
packages/big-design/src/components/Timepicker/index.ts
packages/big-design/src/components/Timepicker/spec.tsx
packages/big-design/src/components/index.ts
packages/big-design/src/utils/localizationProvider/index.ts
packages/big-design/src/utils/localizationProvider/localizationProvider.ts
packages/docs/PropTables/TimepickerPropTable.tsx
packages/docs/PropTables/index.ts
packages/docs/components/SideNav/SideNav.tsx
packages/docs/next.config.js
packages/docs/pages/Datepicker/DatepickerPage.tsx
packages/docs/pages/Timepicker/TimepickerPage.tsx

Adds the `Timepicker` component.
ping @bigcommerce/frontend @chanceaclark

feat(component): add Timepicker component

---

packages/big-design/src/components/Typography/Typography.tsx
packages/big-design/src/components/Typography/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Typography/index.ts
packages/big-design/src/components/Typography/private.ts
packages/big-design/src/components/Typography/spec.tsx
packages/big-design/src/components/Typography/styled.tsx
packages/big-design/src/components/Typography/types.ts
packages/docs/PropTables/TypographyPropTable.tsx
packages/docs/pages/Typography/TypographyPage.tsx

Adds a Horizontal Rule (`HR`) component.

feat(component): add HR component

---

package.json
packages/big-design-icons/package.json
packages/big-design-theme/package.json
packages/big-design/package.json
packages/big-design/setupTests.ts
packages/big-design/src/components/Popover/Popover.tsx
packages/big-design/src/utils/warning/spec.ts
packages/docs/package.json
yarn.lock

Upgrading dependencies to their latest minor/patch versions.

chore(deps): upgrade to latest minors/patches

---

packages/big-design/src/components/List/GroupSeparator/ListGroupSeparator.tsx
packages/big-design/src/components/List/GroupSeparator/styled.tsx

Adjust spacing for ListGroupSeparator to better match what design wants

fix(component): adjust spacing for ListGroupSeparator

---

packages/big-design/src/components/Panel/Panel.tsx
packages/big-design/src/components/Panel/spec.tsx

Forwards ref to `Panel` component.

feat(component): forward ref to Panel component

---

packages/big-design/package.json
packages/big-design/src/components/Dropdown/Dropdown.tsx
packages/big-design/src/components/Dropdown/spec.tsx
packages/big-design/src/components/MultiSelect/MultiSelect.tsx
packages/big-design/src/components/MultiSelect/spec.tsx
packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Pagination/spec.tsx
packages/big-design/src/components/Select/Select.tsx
packages/big-design/src/components/Select/spec.tsx
packages/big-design/src/components/StatefulTable/spec.tsx
packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Table/spec.tsx
packages/big-design/src/components/Timepicker/spec.tsx
yarn.lock

Update `downshift` to use the latest version and make the changes necessary to make it work. Fixed breaking tests due to new changes.
There is a still a performance pass pending but will be done at a different time.

feat: update downshift and fix tests

---

packages/big-design/src/components/Select/Select.tsx
packages/big-design/src/components/Select/spec.tsx

Show icon on selected item
Closes #400

feat(component): show icon on selected item

---

.circleci/config.yml

Bump cache, got messed up in a recent PR.

chore(ci): bump cache version

---

packages/big-design-icons/README.md

Add documentation on how to add new new icons to the library.

docs(icons): add documentation on adding new icons

---

package.json
yarn.lock

Mostly for pre-release support

chore: bump lerna

---

packages/big-design-theme/src/system/colors.ts

Add inherit and transparent props to colors object for use in BD components.

feat(theme): add currentColor, inherit, and transparent props to colors

---

packages/big-design/src/components/Badge/Badge.tsx
packages/big-design/src/components/Badge/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Badge/spec.tsx
packages/big-design/src/components/Badge/styled.tsx
packages/docs/PropTables/BadgePropTable.tsx
packages/docs/pages/Badge/BadgePage.tsx

Adds a primary variant to the badge

feat(component): add primary variant to badge

---

packages/big-design/src/components/Worksheet/Cell/Cell.tsx
packages/big-design/src/components/Worksheet/Cell/styled.tsx
packages/big-design/src/components/Worksheet/Row/Row.tsx
packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Worksheet/editors/SelectEditor/SelectEditor.tsx
packages/big-design/src/components/Worksheet/editors/SelectEditor/index.ts
packages/big-design/src/components/Worksheet/editors/SelectEditor/styled.ts
packages/big-design/src/components/Worksheet/hooks/useEditableCell.ts
packages/big-design/src/components/Worksheet/spec.tsx
packages/big-design/src/components/Worksheet/types.ts

Implements selectable column type
Ongoing development of Worksheet component.
- When clicking on the input directly, there is a small delay on open/closed state change of that component. This can cause an overlap when opening sibling selects. There is no issue if we click on the dropdown button.
- Because of the font resize, the ✔️ icon can be too big, especially when I set the menu as `autoWidth`. Since width is not auto I'm ignoring for now but we might need to revise if we choose to go with that option a later at point.

feat(component): implements selectable column type

---

packages/big-design/src/components/Worksheet/Cell/Cell.tsx
packages/big-design/src/components/Worksheet/Cell/styled.tsx
packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Worksheet/editors/CheckboxEditor/CheckboxEditor.tsx
packages/big-design/src/components/Worksheet/editors/CheckboxEditor/index.ts
packages/big-design/src/components/Worksheet/editors/CheckboxEditor/styled.ts
packages/big-design/src/components/Worksheet/editors/index.ts
packages/big-design/src/components/Worksheet/spec.tsx
packages/big-design/src/components/Worksheet/types.ts

Implements checkbox column type
Ongoing development of Worksheet component.

feat(component): implements checkbox column type

---

packages/docs/components/SideNav/SideNav.tsx

fix(docs): update inline-message side nav link

---

packages/big-design/src/components/Worksheet/Cell/Cell.tsx
packages/big-design/src/components/Worksheet/Modal/Modal.tsx
packages/big-design/src/components/Worksheet/Modal/index.ts
packages/big-design/src/components/Worksheet/Row/Row.tsx
packages/big-design/src/components/Worksheet/Worksheet.tsx
packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Worksheet/editors/ModalEditor/ModalEditor.tsx
packages/big-design/src/components/Worksheet/editors/ModalEditor/index.ts
packages/big-design/src/components/Worksheet/editors/ModalEditor/styled.ts
packages/big-design/src/components/Worksheet/editors/SelectEditor/SelectEditor.tsx
packages/big-design/src/components/Worksheet/editors/index.ts
packages/big-design/src/components/Worksheet/hooks/useStore.ts
packages/big-design/src/components/Worksheet/spec.tsx
packages/big-design/src/components/Worksheet/types.ts

https://user-images.githubusercontent.com/196129/117721684-c94e3c80-b1a5-11eb-8620-fa32275a72db.mp4
Implement Modal type. 
Column of type `modal` has a `config` object that will receive a component to render, passing the value of the selected cell and a callback to set a new value.
```  
config: {
header?: string;
render(
value: Item[keyof Item],
onChange: (value: Item[keyof Item]) => void,
): React.ComponentType<Item> | React.ReactElement;
};
type: 'modal';
```

feat(component): implements modal column type

---

package.json
packages/big-design-theme/package.json
packages/big-design/package.json
yarn.lock

Updates security vulnerabilities.
See https://github.com/bigcommerce/big-design/security/dependabot.

chore(deps): update deps for security vulnerabilities

---

packages/docs/PropTables/WorksheetPropTable.tsx
packages/docs/PropTables/index.ts
packages/docs/components/SideNav/SideNav.tsx
packages/docs/next.config.js
packages/docs/pages/Worksheet/WorksheetPage.tsx

feat: add worksheet docs

---

packages/big-design/src/components/Select/spec.tsx

Refactor tests just like #567 
Tests were too slow and causing timeouts.
Before:
`PASS  src/components/Select/spec.tsx (57.462s)`
After:
`PASS  src/components/Select/spec.tsx (26.159s)`

test(component): update Select tests to have less timeouts

---

README.md

Adds documentation to the README on how to release BigDesign.
So I don't mess up the changelog anymore 😅

chore: add release documentation

---

packages/docs/next-env.d.ts

Adds types generated by the new version of NextJS.

chore(docs): add next image types

---

packages/big-design-icons/package.json
packages/big-design-theme/package.json
packages/big-design/package.json
packages/configs/babel/babel.config.js
packages/docs/package.json
packages/examples/package.json
yarn.lock

Upadte babel configs
First step in updating the build pipeline, this improves build times by ~50%

chore(configs): update babel configs

---

packages/docs/pages/box.tsx

Updates Box page to use new layout
Local

feat(docs): update box page to use new layout

---

packages/docs/pages/counter.tsx

Update counter page to use new layout.
N/A

feat(docs): update counter page to use new layout

---

packages/docs/pages/stepper.tsx

Update `Stepper` page to new format.
N/A

feat(docs): update stepper  page to use new layout

---

packages/docs/pages/switch.tsx

Update `Switch` page to use new layout.
N/A

feat(docs): update switch page to use new layout

---

packages/docs/PropTables/WorksheetPropTable.tsx
packages/docs/components/PropTable/PropTable.tsx
packages/docs/pages/worksheet.tsx

Update `Worksheet` page to use new layout
N/A

feat(docs): update worksheet page to use new layout

---

packages/docs/PropTables/TabsPropTable.tsx
packages/docs/pages/tabs.tsx

Update Tabs page to use new layout.
N/A

feat(docs): update tabs page to use new layout

---

packages/big-design/src/components/Fieldset/Legend/styled.tsx
packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap

Changes the `Fieldset` legend styles from `H3` to `H4`
To comply with design guidelines
Computed font-size 20px
Computed font-size 16px

fix(component): change fieldset legend style from h3 to h4

---

packages/docs/pages/grid.tsx

fix(docs): correct indentation on grid example. (#656)

---

packages/big-design/src/components/PillTabs/PillTabs.tsx
packages/big-design/src/components/PillTabs/__snapshots__/spec.tsx.snap
packages/big-design/src/components/PillTabs/spec.tsx

Accounts for a use case where users need to update the `items` prop in `PillTabs` 
Addresses https://github.com/bigcommerce/big-design/issues/664
Filters might be computed from async sources and thus the prop needs to be able to handle updates
Adding a `useEffect` path where it checks for id mismatches between `items` and the internal state. This handles the case where pills are added, removed, or swapped
- Verified adding/removing pills via async actions (setTimeout)
- Verified pill swapping works
- Verified scenario via unit tests

fix(component): allows pill tabs to receive updated items

---

packages/docs/pages/grid.tsx

Update grid to use new layout. I'm terrible at copy so need help to fill out info.

feat(docs): update grid page to use new layout

---

packages/docs/pages/popover.tsx

Update Popup page to use new layout.

feat(docs): update popover page to use new layout

---

packages/docs/PropTables/SelectPropTable.tsx
packages/docs/pages/multi-select.tsx

Update MultiSelect documentation page to use the new layout

feat(docs): Update multi select page to use new layout

---

packages/docs/PropTables/PillTabsPropTable.tsx
packages/docs/pages/pill-tabs.tsx

Update pill tabs to use new layout.

feat(docs): update Pill tabs to use new layout

---

packages/docs/pages/search.tsx

Update search page to use new layout

feat(docs): update search page to use new layout

---

packages/docs/PropTables/SelectPropTable.tsx
packages/docs/pages/select.tsx

Update select page to use new layout

feat(docs): update select page to use new layout

---

packages/docs/pages/input.tsx

Update input page to use new layout.
Provide better experience to the user when reading or checking the docs.

feat(docs): update input page to use new layout

---

packages/big-design/src/components/Table/Actions/styled.tsx
packages/big-design/src/components/Table/DataCell/styled.tsx
packages/big-design/src/components/Table/HeaderCell/styled.tsx
packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap

1. Update table header row paddings;
2. Update table row paddings;
3. Update table header background-color
4. Update table header font color
To follow the new guideline;
Locally.

chore(component): minor table updates

---

packages/big-design/src/components/Table/Actions/styled.tsx
packages/big-design/src/components/Table/DataCell/styled.tsx
packages/big-design/src/components/Table/HeaderCell/styled.tsx
packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap

1. Update table header row paddings;
2. Update table row paddings;
To follow the new guideline;
Locally.

chore(component): update table rows paddings

---

packages/docs/components/ColorCards/ColorCard.tsx

Forgot to remove `?` in a logic that is no longer necessary.
n/a
n/a

fix(docs): Update colors doc page

---

packages/big-design-icons/tsconfig.json
packages/big-design-theme/tsconfig.json
packages/docs/package.json

Fixes some build issues we were having with some dep updates.
Was unable to release because of these issues.
N/A
See CI.

chore: fix tsconfig include field

---

packages/big-design/src/components/Worksheet/Worksheet.tsx

Fix extra triggering of onChange (Worksheet)
When passing new items to the `Worksheet` component, it triggers the calling of the `onCange` prop, but it should not be called.
Example:
Every 10 seconds is passing the new array of items to `Worksheet`, thereby causing extra calling of the `onChange`.
https://user-images.githubusercontent.com/84462142/176772838-e8a0959e-cb19-4e05-9768-c254204676d8.mov
Locally.

fix(component): fix extra triggering of onChange (Worksheet)

---

packages/big-design/jest.config.js
packages/big-design/src/components/Worksheet/Cell/Cell.tsx
packages/big-design/src/components/Worksheet/Cell/styled.tsx
packages/big-design/src/components/Worksheet/Row/Row.tsx
packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Worksheet/hooks/index.ts
packages/big-design/src/components/Worksheet/hooks/useAutoFilling/index.ts
packages/big-design/src/components/Worksheet/hooks/useAutoFilling/useAutoFilling.ts
packages/big-design/src/components/Worksheet/hooks/useWorksheetStore/useWorksheetStore.ts
packages/big-design/src/components/Worksheet/spec.tsx

1. Auto-filing of the full column by the value from the double-clicked "auto-fill" handler.
2. Auto-filing of the multiple cells by dragging the "auto-fill" handler.
3. Selection of the multiple cells by dragging the pointer after the mouse down.
To extend the worksheet with the new functionality.
https://user-images.githubusercontent.com/84462142/216976501-0f552c02-584f-4e0d-b89b-e8e2931efc77.mov
Locally.

feat(component): copy content within the column (worksheet)

---

packages/big-design/src/components/Worksheet/hooks/useAutoFilling/useAutoFilling.ts

Prevent filling out the disabled cells
https://github.com/bigcommerce/big-design/assets/84462142/fb0cce5c-5348-4d97-b19e-7ea6c272af0c
Locally.

fix(component): prevent filling out the disabled cells

---

packages/big-design/src/components/Worksheet/hooks/useAutoFilling/useAutoFilling.ts
packages/big-design/src/components/Worksheet/spec.tsx

Fix the filling of the disabled worksheet rows.
https://github.com/bigcommerce/big-design/assets/84462142/915f69b4-b4b1-46e5-a2ba-58f943ed97bb
Locally.

fix(component): fix the filling of the disabled worksheet rows

---

packages/big-design/src/components/Worksheet/hooks/useAutoFilling/useAutoFilling.ts

Fix the selection issue when the table consists of many items.
BEFORE FIX
https://github.com/bigcommerce/big-design/assets/84462142/302c7178-232e-4c05-aa21-7d90f7b52ecf
AFTER FIX
https://github.com/bigcommerce/big-design/assets/84462142/1d3091fc-ba60-4a9f-b627-0f8b1e11478e
Locally.

fix(component): fix selection issue when many items

---

packages/big-design-icons/src/components/FileDownloadIcon.tsx
packages/big-design-icons/src/components/index.ts
packages/big-design-icons/svgs/material/file_download.svg

Add <FileDownloadIcon />
Locally.

feat(icons): add FileDownloadIcon

---

packages/big-design/src/components/StatefulTree/spec.tsx
packages/big-design/src/components/Worksheet/hooks/useAutoFilling/useAutoFilling.ts

Fix autofilling for disabled cells.
https://github.com/bigcommerce/big-design/assets/84462142/7c6b26e0-b99f-48bc-985d-e517c315c5f9
Locally + UT

fix(component): fix autofilling for disabled cells

---

packages/docs/design-docs/ux-writing/index.mdx

* Changes the `glossary` icon in the UX Writing Guide
* Per design from @bc-ghough
This is a component library so we love visually looking at changes! If this applies to your pull request, show us your hard work in action.
Explain how you tested your new feature or bugfix. Please refrain from one-liners like, `Added tests.`; expand upon how you tested your changes like, `Added local tests to the new component and ensured test coverage was met. Manually tested on Safari@x.x.x.`.
ping @davelinke @bc-ghough

docs: update glossary component to support dev center

---

packages/docs/design-docs/ux-writing/index.mdx

Some paths were changed on the developer center's end, but the components in this repo weren't updated to reflect that. This PR fixes that 🤞

Update hrefs on landing cards

---

packages/docs/design-docs/ux-writing/index.mdx
packages/docs/design-docs/ux-writing/status-messages.mdx
packages/docs/design-docs/ux-writing/the-basics.mdx
packages/docs/design-docs/ux-writing/writing-for-mobile.mdx

Describe what changes you are making. e.g. `Adds X prop in the Box component.`
* upcase titles
Please provide the reason(s) why you are making this change? Please no one-liners like, `It was missing.`; expand upon the reason like, `Adds X prop because it was missing in the Box component. Documentation notes this prop exists, but it actually wasn't implemented.`
* the Dev Center uses title case titles and sentence case headings inside each doc. the Guide now conforms to that.
This is a component library so we love visually looking at changes! If this applies to your pull request, show us your hard work in action.
Explain how you tested your new feature or bugfix. Please refrain from one-liners like, `Added tests.`; expand upon how you tested your changes like, `Added local tests to the new …

fix(docs): minor UX Writing Guide copy to match Dev Center IA conventions

---

packages/docs/design-docs/ux-writing/index.mdx

Describe what changes you are making. e.g. `Adds X prop in the Box component.`
* update links in UX writing guide following dev center menu updates
Please provide the reason(s) why you are making this change? Please no one-liners like, `It was missing.`; expand upon the reason like, `Adds X prop because it was missing in the Box component. Documentation notes this prop exists, but it actually wasn't implemented.`
* update links in UX writing guide following dev center menu updates
This is a component library so we love visually looking at changes! If this applies to your pull request, show us your hard work in action.
Explain how you tested your new feature or bugfix. Please refrain from one-liners like, `Added tests.`; expand upon how you tested your changes like, `Added local tests to …

chore(fix): update links in UX writing guide

---

packages/big-design/src/components/FileUploader/DropZone.tsx
packages/big-design/src/components/FileUploader/File.tsx
packages/big-design/src/components/FileUploader/FileUploader.tsx
packages/big-design/src/components/FileUploader/index.ts
packages/big-design/src/components/FileUploader/spec.tsx
packages/big-design/src/components/FileUploader/styled.ts
packages/big-design/src/components/FileUploader/utils/index.ts
packages/big-design/src/components/FileUploader/utils/loadImagePreview.ts
packages/big-design/src/components/FileUploader/utils/spec.ts
packages/big-design/src/components/FileUploader/utils/validateFile.ts
packages/big-design/src/components/Form/styled.tsx
packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
packages/big-design/src/components/TableNext/RowContainer/spec.ts
packages/big-design/src/components/TableNext/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Textarea/__snapshots__/spec.tsx.snap
packages/big-design/src/components/Tooltip/spec.tsx
packages/big-design/src/components/index.ts
packages/docs/PropTables/FileUploaderPropTable.tsx
packages/docs/PropTables/index.ts
packages/docs/components/SideNav/SideNav.tsx
packages/docs/pages/file-uploader.tsx

Create `FileUploader` component.

feat(component): create file uploader

---

packages/big-design/src/components/Dropdown/Dropdown.tsx
packages/big-design/src/components/Dropdown/spec.tsx
packages/big-design/src/components/Dropdown/types.ts
packages/big-design/src/components/Pagination/Pagination.tsx
packages/big-design/src/components/Pagination/spec.tsx

Fixes #512
Added local tests to the new component and ensured test coverage was met.

fix: highlight correct pagniation item

---

package.json
packages/big-design/src/components/AccordionPanel/spec.tsx
packages/big-design/src/components/Alert/spec.tsx
packages/big-design/src/components/Button/spec.tsx
packages/big-design/src/components/ButtonGroup/spec.tsx
packages/big-design/src/components/Checkbox/spec.tsx
packages/big-design/src/components/Chip/spec.tsx
packages/big-design/src/components/Collapse/spec.tsx
packages/big-design/src/components/Counter/spec.tsx
packages/big-design/src/components/Datepicker/spec.tsx
packages/big-design/src/components/Dropdown/spec.tsx
packages/big-design/src/components/FileUploader/spec.tsx
packages/big-design/src/components/MultiSelect/spec.tsx
packages/big-design/src/components/Pagination/spec.tsx
packages/big-design/src/components/PillTabs/spec.tsx
packages/big-design/src/components/Select/spec.tsx
packages/big-design/src/components/StatefulTree/spec.tsx
packages/big-design/src/components/Switch/spec.tsx
packages/big-design/src/components/Table/spec.tsx
packages/big-design/src/components/TableNext/spec.tsx
packages/big-design/src/components/Tabs/spec.tsx
packages/big-design/src/components/Tree/spec.tsx
packages/big-design/src/components/Worksheet/spec.tsx

Fixes eslint warnings we were having in the repo. Also disables warnings from making it through CI.
Cleanup of the repo.
N/A
See CI.

chore: fix and disable eslint warnings

---

README.md

Add instructions on how to update snapshots when needed.
I forget literally every time and spend 30 minutes searching my shell history to remember what commands I need to run and where.

docs(release): document process for updating snapshots

---

CONTRIBUTING.md
README.md
packages/docs/CHANGELOG.md
packages/docs/PAGES.md
packages/docs/pages/index.tsx

Describe what changes you are making. e.g. `Adds X prop in the Box component.`
* Updating links
Please provide the reason(s) why you are making this change? Please no one-liners like, `It was missing.`; expand upon the reason like, `Adds X prop because it was missing in the Box component. Documentation notes this prop exists, but it actually wasn't implemented.`
* Because they were broken. Chiefly, links to design.bigcommerce.com
This is a component library so we love visually looking at changes! If this applies to your pull request, show us your hard work in action.
Explain how you tested your new feature or bugfix. Please refrain from one-liners like, `Added tests.`; expand upon how you tested your changes like, `Added local tests to the new component and ensured test coverage was met. …

docs(chore): update links

---

.github/workflows/changesets.yml

Updates the commit message of changesets to be in line with our commitlint rules.
N/A

chore: update the commit message for changesets

---

.vscode/settings.example.json

chore: add vscode example settings

---

.changeset/brown-bags-complain.md
.circleci/config.yml
commitlint.config.js
packages/big-design-patterns/.eslintrc.js
packages/big-design-patterns/README.md
packages/big-design-patterns/babel.config.js
packages/big-design-patterns/jest.config.js
packages/big-design-patterns/package.json
packages/big-design-patterns/setupTests.ts
packages/big-design-patterns/src/utils/env.ts
packages/big-design-patterns/src/utils/index.ts
packages/big-design-patterns/src/utils/warning/index.ts
packages/big-design-patterns/src/utils/warning/spec.ts
packages/big-design-patterns/src/utils/warning/warning.ts
packages/big-design-patterns/tsconfig.declarations.json
packages/big-design-patterns/tsconfig.json
pnpm-lock.yaml

Adds the initial package files for `@bigcommerce/big-design-patterns`.
We will be introducing this new package that will contain consistent and reusable patterns we've seen throughout the control panel.
N/A
N/A

feat(patterns): initialize patterns package

---

.changeset/brown-bags-complain.md
packages/big-design-patterns/src/components/Page/Page.tsx
packages/big-design-patterns/src/components/Page/index.ts
packages/big-design-patterns/src/components/Page/spec.tsx
packages/big-design-patterns/src/components/Page/styled.tsx
packages/big-design-patterns/src/components/index.ts

Adds a `Page` component which enforces page width, spacing, and background image. Supports adding a `Header` component and a `Message` component.
To enforce page level layouts.
Added unit test + local testing with this code:
<details>
<summary><code>dev.tsx</code> code</summary>
```tsx
import { Link, Panel, Text } from '@bigcommerce/big-design';
import { AddIcon, ArrowDropDownIcon } from '@bigcommerce/big-design-icons';
import { Header, Page } from '@bigcommerce/big-design-patterns';
import React from 'react';
export default function DevPage() {
return (
<Page
background={{
src: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwMCIgaGVpZ2h0PSI4OTciIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgY2xpcC1wYXRoPSJ1cmwoI2EpIj48cGF0aCBmaWxsPSIjRjZGN0ZDIiBkPSJNMCAwaDEwMDB2ODk3SDB …
```

feat(patterns): implement the Page component

---

.changeset/brown-bags-complain.md

Updates the patterns changeset to include the new patterns.
To document usage of the new components and present a good changelog.
N/A
N/A

chore: update changeset with usage of new patterns

---

.changeset/nine-wasps-camp.md
packages/big-design-patterns/src/components/ActionBar/styled.tsx
packages/big-design-patterns/src/components/Page/Page.tsx
packages/big-design-patterns/src/components/Page/styled.tsx

Refactors the Page and ActionBar components to be able to work within iframeless contexts.
Shout out to @deini for the CSS approach here 🙏 
Reran the tests and cover and nothing is off.

refactor(patterns): update page + actionbar to work outside iframes

---

.changeset/modern-crabs-push.md

Add `changeset` to trigger release. It will update minor version of `BigDesign` according to new `FileUpload` interface and feature.

chore(release): add changeset to trigger release

---

.changeset/dull-boats-rule.md

Add `changeset` to trigger release. It will update minor version of `BigDesign` to include the new Pin icon

chore(icons): add changeset to release trigger release
