- packages/docs/pages/Flex/FlexPage.tsx
- packages/docs/pages/Grid/GridPage.tsx
- packages/docs/pages/Panel/PanelPage.tsx
`Flex/Grid` should show `Box` props, but not `Panel`
> fix(docs): add missing docs for Flex/Grid

- lerna.json
Ignore some files on `lerna diff/changed`. This will avoid some unnecessary version bumps, for eg: [big-design-theme 0.1.1](https://github.com/bigcommerce/big-design/blob/master/packages/big-design-theme/CHANGELOG.md) which was released because we made a change to its `README.md`.
> chore: lerna ignore changes in .md and specs

- packages/big-design-theme/src/system/z-index.ts
- packages/big-design/src/components/List/styled.tsx
- packages/big-design/src/components/Modal/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Modal/styled.tsx
- packages/big-design/src/components/Tooltip/styled.tsx
- packages/docs/components/SideNav/SideNavMenu/styled.tsx
z-indexes were missing on some components. Also removed dropdown since it didn't make sense for our component use-cases.
> fix(component): add missing z-index to components

- packages/big-design/src/index.ts
Exported `MarginProps`, `PaddingProps`, `withMargins()`, and `withPadding()`.
> fix: export margin and padding mixins/functions

- packages/docs/components/CodePreview/CodePreview.tsx
- packages/docs/components/CodeSnippet/CodeSnippet.tsx
- packages/docs/package.json
- packages/docs/pages/Box/BoxPage.tsx
- packages/docs/pages/Breakpoints/BreakpointsPage.tsx
- yarn.lock
Shoutouts to @sofiapoh for https://github.com/FormidableLabs/react-live/pull/159 we no longer need to do our hacky transform to support template strings.
> refactor(docs): no longer need to transform react-live code

- packages/big-design/src/components/Form/Group/Group.tsx
- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Input/spec.tsx
- packages/docs/PropTables/FormPropTable.tsx
- packages/docs/PropTables/InputPropTable.tsx
Add ability to pass in an array of strings into `Input`'s.
Also noticed that `React.ReactChild` includes strings, so removed erroneous `string` type declarations.
> feat(component): add ability to pass arrays into input error

- packages/big-design/src/components/Link/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Link/styled.tsx
The Link component is not using font configs from the theme, hence if you have an html font size different than 16, the link component does not scale correctly, I believe this is a bug
> fix(component): use font configs for link component

- packages/big-design/src/components/Textarea/Textarea.tsx
- packages/big-design/src/components/Textarea/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Textarea/spec.tsx
- packages/big-design/src/components/Textarea/styled.tsx
> fix(component): textarea rendering two errors

- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/Select/Select.tsx
- packages/docs/PropTables/SelectPropTable.tsx
By default we use `absolute` to position a Select list, this prop allows changing the positioning strategy to use `fixed`
> feat(component): add `positionFixed` prop to Select

- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
Updates the input text of a Select component if a matching children suddenly appears within its children
- Verified bug cant be reproduced anymore
- Unit test
> fix: updates the input label if a matching children appears

- packages/big-design/__mocks__/popper.js.ts
- packages/big-design/src/components/Dropdown/spec.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/docs/PropTables/PaginationPropTable.tsx
- Mocks popper.js globally in our tests, this fixes an unhandled warning.
- Add `.` to pagination prop table
> fix: tests unhandled warnings

- packages/docs/pages/Pagination/PaginationPage.tsx
Removing design link till Product Design gets the page up.
> fix(docs): temporarily remove design guideline navigation link

- packages/docs/pages/GettingStarted/GettingStartedPage.tsx
**What**
Added links in Helpful Resources section for Figma UI Kit and sample app. 
**Why**
https://jira.bigcommerce.com/browse/CHP-6053
To provide developers and designers with more resources to help them in building apps with BigDesign
> feat(docs): add figma UI kit and sample app to resources section

- packages/big-design/src/components/Checkbox/Checkbox.tsx
- packages/big-design/src/components/Checkbox/spec.tsx
- packages/big-design/src/components/Checkbox/styled.tsx
- packages/big-design/src/components/Chip/Chip.tsx
- packages/big-design/src/components/Chip/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/spec.tsx
- packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/styled.tsx
- packages/big-design/src/components/List/Action/Action.tsx
- packages/big-design/src/components/List/Item/CheckboxItem.tsx
- packages/big-design/src/components/List/Item/Item.tsx
- packages/big-design/src/components/List/Item/styled.tsx
- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/big-design/src/components/Select/styled.tsx
- packages/docs/PropTables/SelectPropTable.tsx
- packages/docs/pages/Select/SelectPage.tsx
Multi selectable component. Using the same `select` component but with an added `multi` prop that enables `checkboxes` on all items. Allows multiple checked elements.
Still using the same `value` and `onItemClick` props to return the selected items. In the case of being a `multi` select we return an `array` of values selected.
> feat(component): add multiselect

- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/index.ts
- packages/big-design/src/components/Dropdown/spec.tsx
- packages/big-design/src/components/Dropdown/types.ts
- packages/big-design/src/components/List/Item/Item.tsx
- packages/big-design/src/components/List/Item/styled.tsx
- packages/big-design/src/components/Pagination/Pagination.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/docs/PropTables/DropdownPropTable.tsx
- packages/docs/pages/Dropdown/DropdownPage.tsx
Added new `options` prop that will restrict the usage of the items. The `onClick` for each item with return the `item` itself. No need to use `data-value` anymore.
Now also accepts `icons` as a DropdownItem prop.
Wasn't sure how to document the new `DropdownItem` and `DropdownLinkItem`. Feedback pls 🙏 .
> Restrict Dropdown

- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Input/spec.tsx
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
Reverts the addition of customValidity logic for inputs and selects
1) The logic is buggy
2) It is not something the input itself should handle
3) Clashes with design guidelines if users don't use `noValidate`, which is an issue
> chore: revert customValidity logic

- packages/big-design/src/components/Tabs/Tabs.tsx
- packages/big-design/src/components/Tabs/index.ts
- packages/big-design/src/components/Tabs/styled.tsx
- packages/docs/PropTables/TabsPropTable.tsx
- packages/docs/pages/Tabs/TabsPage.tsx
Restrict Tabs to accept a configurable object.
BREAKING CHANGE: Tabs now accepts an `items` prop to render tab items and omits children from being rendered.
Old:
```jsx
<Tabs>
<Tabs.Tab id="tab1">Tab 1</Tabs.Tab>
{/* ... */}
</Tabs>
```
New:
```jsx
<Tabs activeTab="tab1" items={[{ id: 'tab1', title: 'Tab 1' }]} onTabClick={() => {}} />
```
> feat(component): update Tabs component to be more restrictive

- packages/docs/components/SideNav/styled.tsx
Fix logo overflowing into side nav in Safari.
Old:
New:
> fix(docs): logo overflowing into side nav

- packages/big-design/src/components/List/Item/styled.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Select/spec.tsx
- packages/big-design/src/components/Select/styled.tsx
- packages/big-design/src/components/Select/types.ts
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/docs/PropTables/SelectPropTable.tsx
- packages/docs/pages/Select/SelectPage.tsx
Functionality will remain the same by default, but now it can be set to `false` to prevent input filtering.
Misc:
Added back the `label` styling rule, it was actually needed.
> feat(component): add filterable prop to Select

- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/types.ts
Adds a `name` prop to the `Select` component and forwards that to the rendered `input` element
- Verified the name prop is forwarded to the actual HTML input element
> fix: adds name prop to select

- packages/big-design/src/components/StatefulTable/StatefulTable.tsx
- packages/big-design/src/components/StatefulTable/index.ts
- packages/big-design/src/components/StatefulTable/reducer.ts
- packages/big-design/src/components/StatefulTable/spec.tsx
- packages/big-design/src/components/Table/SelectAll/SelectAll.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/styled.tsx
- packages/big-design/src/components/Table/types.ts
- packages/big-design/src/components/index.ts
- packages/big-design/src/utils/useDidUpdate.ts
- packages/docs/PropTables/StatefulTablePropTable.tsx
- packages/docs/PropTables/TablePropTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/next.config.js
- packages/docs/pages/Button/ButtonPage.tsx
- packages/docs/pages/StatefulTable/StatefulTablePage.tsx
- packages/docs/pages/Table/TablePage.tsx
Adds a `<StatefulTable />` component to be used when having access to the full items list in memory. Handles all pagination, sorting, selection logic internally.
BREAKING CHANGE: `<Table />` no longer accepts Margin props.
> feat(component): stateful table

- packages/docs/pages/Table/TablePage.tsx
Simplify `<Table />` docs by splitting a complex table into 3 sections:
- Sortable
- Pagination
- Sorting
> feat(docs): split table docs

- packages/big-design/src/components/Table/HeaderCell/HeaderCell.tsx
- packages/big-design/src/components/Table/HeaderCell/styled.tsx
- packages/big-design/src/components/Table/spec.tsx
`align` prop on table headers broke after introducing sorting.
> fix(component): table header not aligning properly

- packages/big-design-theme/src/system/z-index.ts
- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/spec.tsx
- packages/big-design/src/components/Dropdown/types.ts
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tooltip/Tooltip.tsx
- packages/big-design/src/components/Tooltip/index.ts
- packages/big-design/src/components/Tooltip/styled.tsx
- packages/docs/PropTables/DropdownPropTable.tsx
- packages/docs/pages/Dropdown/DropdownPage.tsx
Added support for tooltip in `<Dropdown />` component item.
> feat(component): tooltip for dropdown item

- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/big-design/src/components/Select/types.ts
- packages/docs/PropTables/SelectPropTable.tsx
The `Select` component now accepts an optional `inputRef` of type `RefObject<HTMLInputElement> | React.Ref<HTMLInputElement>`
The prop accepts three usages:
- `inputRef={undefined}`
- `inputRef={React.createRef<HTMLInputElement>()}`
- `inputRef={(input: HTMLInputElement) => void}`
> feat: CHI-696 select component accepts an inputRef prop

- packages/big-design/__mocks__/popper.js.ts
- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/Table/Actions/Actions.tsx
- packages/big-design/src/components/Table/Actions/styled.tsx
- packages/big-design/src/components/Table/HeaderCell/HeaderCell.tsx
- packages/big-design/src/components/Table/HeaderCell/styled.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tooltip/Tooltip.tsx
- packages/big-design/src/utils/useComponentSize.ts
- packages/docs/PropTables/TablePropTable.tsx
- packages/docs/components/BetaRibbon/styled.tsx
- packages/docs/pages/StatefulTable/StatefulTablePage.tsx
- packages/docs/pages/Table/TablePage.tsx
Add stickiness to table actions.
Other changes:
- enable/disable Popper event listeners if the container is displaying or not. This was causing a rerender on scroll to the `InnerPopper` element.
- increased the z-index of the Beta Ribbon.
> feat(component): add stickiness to table header and actions

- packages/big-design/src/components/Box/Box.tsx
- packages/big-design/src/components/Box/spec.tsx
- packages/docs/PropTables/BoxPropTable.tsx
Change the rendered Tag / Component at runtime
```jsx
<Box as="section" />
```
This will render a `<section>` instead of a `<div>`.
> feat(component): allow Box to render with a different tag

- packages/big-design/src/components/Box/Box.tsx
- packages/big-design/src/components/Box/styled.tsx
- packages/big-design/src/components/Flex/styled.tsx
- packages/big-design/src/components/Grid/styled.tsx
- packages/big-design/src/mixins/display/__snapshots__/spec.tsx.snap
- packages/big-design/src/mixins/display/display.tsx
- packages/big-design/src/mixins/display/index.ts
- packages/big-design/src/mixins/display/spec.tsx
- packages/big-design/src/mixins/display/types.ts
- packages/big-design/src/mixins/index.ts
- packages/docs/PropTables/DisplayPropTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/next.config.js
- packages/docs/pages/Box/BoxPage.tsx
- packages/docs/pages/Display/DisplayPage.tsx
- packages/docs/pages/Flex/FlexPage.tsx
- packages/docs/pages/Grid/GridPage.tsx
Adds a `display` prop to some of our utility components. Useful for layouts that require responsive displays (i.e. "none" on mobile, "block" on table+) and other usefulness.
> feat(component): add display prop to utility components

- packages/big-design/src/components/Link/Link.tsx
- packages/big-design/src/components/Link/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Link/spec.tsx
- packages/big-design/src/components/Link/styled.tsx
- packages/docs/PropTables/LinkPropTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/pages/Link/LinkPage.tsx
Add the ability to pass icons to `Link` components. Should help with #236.
> feat(component): add icon props to link component

- packages/big-design/src/components/Checkbox/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Checkbox/styled.tsx
- packages/big-design/src/components/Radio/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Radio/styled.tsx
Spacing between checkbox/radio and their label should be `8px` and not `16px`.
> fix(component): reduce radio/checkbox label margin

- packages/big-design-icons/package.json
- packages/big-design-theme/package.json
- packages/big-design/package.json
- packages/big-design/src/components/Flex/Flex.tsx
- packages/big-design/src/components/Flex/Item/Item.tsx
- packages/big-design/src/components/Flex/Item/styled.tsx
- packages/big-design/src/components/Flex/spec.tsx
- packages/big-design/src/components/Flex/styled.tsx
- packages/big-design/src/components/Grid/Grid.tsx
- packages/big-design/src/components/Grid/Item/Item.tsx
- packages/big-design/src/components/Grid/Item/styled.tsx
- packages/big-design/src/components/Grid/spec.tsx
- packages/big-design/src/components/Grid/styled.tsx
- packages/docs/package.json
- yarn.lock
`Grid` and `Flex` internally extend `Box` using `styled(Box)`. The issue is now that we introduced the `as` prop for util components when doing something like:
```jsx
<Flex as="section" />
```
This will swap that `styled(Box)` with `styled('section')`, which in this case is not exactly what we want since we lose all the functionality from `Box` like `margin` props, etc.
styled-components `4.3` introduced a `forwardedAs` prop for this specific use case. So doing something like this would work:
```jsx
<Flex forwardedAs="section" />
```
However, it is inconsistent with `Box` and requires the user to know how `Flex` and `Grid` are implemented. This PR makes `Grid` and `Flex` accept an `as` prop but internally swap them with `forwardedAs`.
Gotchas:
- Breaking change since had to bump SC peer …
> fix(component): grid and flex forward as prop

- packages/docs/PropTables/CheckboxPropTable.tsx
- packages/docs/pages/Checkbox/CheckboxPage.tsx
- packages/docs/pages/Grid/GridPage.tsx
Remove duplicate headings:
```html
<h2>Checkbox</h2>
<h2>Checkbox</h2>
```
> fix(docs): remove duplicate headings

- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/big-design/src/components/Select/types.ts
- packages/docs/PropTables/SelectPropTable.tsx
- packages/docs/pages/Form/FormPage.tsx
- packages/docs/pages/Select/SelectPage.tsx
See `BREAKING CHANGE` below.
`onChange` is renamed to `onItemChange`
> feat(component): change Select onChange to be a synthetic event

- packages/big-design/src/components/Select/Select.tsx
- packages/docs/pages/Select/SelectPage.tsx
I want to enforce `options` to have a `value`, therefore I validate if it is set. Before it wouldn't allow `0` as a valid value.
Fixed the width of selects in docs.
> fix(component): allow 0 as values in select and fix docs

- packages/big-design/src/components/Textarea/Textarea.tsx
- packages/big-design/src/components/Textarea/__snapshots__/spec.tsx.snap
Fix `Textarea` not rendering `(optional)`.
**Before:**
**After:**
> fix(component): textarea was missing optional text when not required

- packages/big-design/src/components/StatefulTable/spec.tsx
- packages/big-design/src/components/Table/Actions/Actions.tsx
- packages/big-design/src/components/Table/SelectAll/SelectAll.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/TablePagination/TablePagination.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/Table/types.ts
- packages/docs/PropTables/StatefulTablePropTable.tsx
- packages/docs/PropTables/TablePropTable.tsx
Allow `customActions` in `<Table>` and `<StatefulTable>`
Example:
> feat(component):  add actions prop to Table and StatefulTable

- packages/big-design/src/components/Checkbox/Checkbox.tsx
- packages/big-design/src/components/Checkbox/styled.tsx
- packages/big-design/src/components/Table/Row/Row.tsx
- packages/big-design/src/components/Table/SelectAll/SelectAll.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/docs/PropTables/CheckboxPropTable.tsx
#WHAT 
Adds `hiddenLabel` prop to Checkbox component to allow for visually hidden label, maintain accessibility. Closes #203.
#TESTING 
Tested locally to ensure prop allows component to render correctly
> feat: add hiddenLabel prop to Checkbox component

- packages/big-design/src/components/Select/Select.tsx
Noticed `ul` element in Selects had an `action` attribute passed on. We use the `action` prop to render the `action` items, but in a different method.
> fix(component): prevent action prop from being passed to List component

- packages/big-design/src/components/Badge/Badge.tsx
- packages/big-design/src/components/Box/Box.tsx
- packages/big-design/src/components/Chip/Chip.tsx
- packages/big-design/src/components/Form/Form.tsx
- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Link/Link.tsx
- packages/big-design/src/components/List/Item/CheckboxItem.tsx
- packages/big-design/src/components/List/Item/Item.tsx
- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/Pagination/Pagination.tsx
- packages/big-design/src/components/Panel/Panel.tsx
- packages/big-design/src/components/Tabs/Tabs.tsx
- packages/big-design/src/components/Textarea/Textarea.tsx
- packages/big-design/src/components/Typography/Typography.tsx
Cleans up React Dev Tools tree view.
Missing components:
- Table
- StatefulTable
We need a better way to memo a generic component and retain native react properties `eg: displayName`
> fix(component): set correct display names

- packages/big-design/package.json
- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/styled.tsx
- yarn.lock
Fix issue with `Selects` having extra spacing, by updating `react-popper` and dependencies and swapping container from `span` to `div`. Using new references as well. Fixed small bug.
> fix: extra spacing in Select components

- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/spec.tsx
When all `options` are disabled, no items are "available" for selection. Now properly validate if `listItemRefs` has items.
> fix(component): properly handle Dropdown if all options are disabled

- packages/big-design/src/components/Pagination/Pagination.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Pagination/spec.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
+ Remove `per page` in Dropdown 
+ Use `iconOnly` buttons.
+ Update tests
Buttons:
Per page gone:
Wonky behavior when hovering:
> fix(component): use iconOnly buttons and remove 'per page' in Pagination

- packages/docs/components/NextLink/NextLink.tsx
This fixes the issue of `NextLinks` with hashes not working in live docs. 
I wasn't able to reproduce this issue locally while `yarn run start`, but verified they don't work on production.
> fix(docs): prevent hashes on links from being overwritten

- commitlint.config.js
- package.json
- yarn.lock
📦 Bump `react-live` which has the updated version of `prism-react-renderer`, we no longer need custom yarn resolutinos.
> chore(docs): bump react-live and remove resolutions

- .gitignore
- package.json
- packages/tests/README.md
- packages/tests/babel.config.js
- packages/tests/functional/basic.ts
- packages/tests/package.json
- packages/tests/wdio.conf.js
1. Adding functional tests in a seperate package
2. Enable standalone-selenium
3. Enable Typescript
4. Enable logging
@aaron-humerickhouse @lorentzkim 
https://github.com/bigcommerce/big-design/pull/278 represents the other approach. However I'm not sure whether browserstack will work well with this approach or not.
> [POC] QPT-7 Establish basic test structure

- packages/big-design/src/components/StatefulTable/spec.tsx
- packages/big-design/src/components/Table/Body/Body.tsx
- packages/big-design/src/components/Table/Body/styled.tsx
- packages/big-design/src/components/Table/DataCell/DataCell.tsx
- packages/big-design/src/components/Table/DataCell/styled.tsx
- packages/big-design/src/components/Table/Head/Head.tsx
- packages/big-design/src/components/Table/Head/styled.tsx
- packages/big-design/src/components/Table/HeaderCell/styled.tsx
- packages/big-design/src/components/Table/Row/styled.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/Table/styled.tsx
- packages/big-design/src/components/Table/types.ts
- packages/docs/PropTables/StatefulTablePropTable.tsx
- packages/docs/PropTables/TablePropTable.tsx
Adds a boolean `hiddenHeaders` to `<Table />` and `<StatefulTable />`.
Headers will be rendered but visually hidden for accessibility purposes.
> feat(component): add hidden headers props to Table and StatefulTable

- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Input/spec.tsx
- packages/big-design/src/components/Textarea/Textarea.tsx
- packages/big-design/src/components/Textarea/spec.tsx
- packages/docs/PropTables/InputPropTable.tsx
- packages/docs/PropTables/TextareaPropTable.tsx
Add `labelId`'s to form fields.
Didn't add it to `Select`'s since #303 covers it.
> feat(component): add label id's to form fields

- packages/big-design/src/components/Link/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Link/styled.tsx
Fixing a small bug in the `Link` component when `external=true`.
Without `flex-shrink: 0` CSS property external icon brings smaller when` Link` component width decrease (pls see example below).
> fix(component): add flex-shrink 0 to external link icon

- packages/big-design/src/components/Typography/spec.tsx
- packages/big-design/src/components/Typography/styled.tsx
- packages/big-design/src/components/Typography/types.ts
- packages/docs/PropTables/TypographyPropTable.tsx
- packages/docs/pages/Typography/TypographyPage.tsx
New text modifiers:
- uppercase
- lowercase
- capitalize
> feat(component): add text-transform props to Text and Small

- packages/big-design/src/components/Modal/Modal.tsx
- packages/big-design/src/components/Modal/spec.tsx
`focus-trap` requires at least one focusable element. Made the modal itself focusable and set it as `initialFocus`.
> fix(component): modal crash with no focusable elements

- packages/big-design/src/components/Form/Description/Description.tsx
- packages/big-design/src/components/Form/Description/index.ts
- packages/big-design/src/components/Form/Error/Error.tsx
- packages/big-design/src/components/Form/Error/index.ts
- packages/big-design/src/components/Form/Form.tsx
- packages/big-design/src/components/Form/Group/Group.tsx
- packages/big-design/src/components/Form/Group/spec.tsx
- packages/big-design/src/components/Form/Label/Label.tsx
- packages/big-design/src/components/Form/Label/index.ts
- packages/big-design/src/components/Form/Label/spec.tsx
- packages/big-design/src/components/Form/index.ts
- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Textarea/Textarea.tsx
Rename and expose form controls in preparation for removing static members on form fields.
_This is how we do it_
> feat(component): rename and expose form controls

- packages/big-design/src/components/Form/Group/spec.tsx
- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Input/spec.tsx
- packages/docs/PropTables/InputPropTable.tsx
- packages/docs/pages/Input/InputPage.tsx
Convert `Input` to functional component and remove static members.
---
Use `FormControlDescription`, `FormControlError`, and `FormControlLabel`
instead of `Input.Description`, `Input.Error`, and `Input.Label` respectively.
> feat(component): convert Input to FC and remove static members

- packages/big-design/src/components/Fieldset/Fieldset.tsx
- packages/big-design/src/components/Fieldset/spec.tsx
- packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/spec.tsx
- packages/big-design/src/components/Textarea/Textarea.tsx
- packages/big-design/src/components/Textarea/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Textarea/spec.tsx
- packages/big-design/src/utils/index.ts
- packages/big-design/src/utils/useUniqueId.ts
- packages/docs/PropTables/TextareaPropTable.tsx
- packages/docs/pages/Textarea/TextareaPage.tsx
Convert `Input` to functional component and remove static members.
---
Use `FormControlDescription`, `FormControlError`, and `FormControlLabel`
instead of `Textarea.Description`, `Textarea.Error`, and `Textarea.Label` respectively.
> feat(component): convert Textarea to FC and remove static members

- packages/big-design/src/components/Checkbox/Checkbox.tsx
- packages/big-design/src/components/Checkbox/Label/Label.tsx
- packages/big-design/src/components/Checkbox/Label/index.ts
- packages/big-design/src/components/Checkbox/Label/styled.tsx
- packages/big-design/src/components/Checkbox/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Checkbox/index.ts
- packages/big-design/src/components/Checkbox/private.ts
- packages/big-design/src/components/Checkbox/spec.tsx
- packages/big-design/src/components/Checkbox/styled.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/docs/PropTables/CheckboxPropTable.tsx
Convert `Checkbox` to a functional component and remove static members.
---
Use `CheckboxLabel` instead of `Checkbox.Label`.
> feat(component): convert Checkbox to FC and remove static members

- packages/big-design/src/components/Radio/Label/Label.tsx
- packages/big-design/src/components/Radio/Label/index.ts
- packages/big-design/src/components/Radio/Label/styled.tsx
- packages/big-design/src/components/Radio/Radio.tsx
- packages/big-design/src/components/Radio/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Radio/index.ts
- packages/big-design/src/components/Radio/private.ts
- packages/big-design/src/components/Radio/spec.tsx
- packages/big-design/src/components/Radio/styled.tsx
- packages/docs/PropTables/RadioPropTable.tsx
Convert `Radio` to a functional component and remove static members.
---
Use `RadioLabel` instead of `Radio.Label`.
> feat(component): convert Radio to FC and remove static members

- packages/big-design/setupTests.ts
- packages/big-design/src/components/Checkbox/spec.tsx
- packages/big-design/src/components/Form/Form.tsx
- packages/big-design/src/components/Form/Group/Group.tsx
- packages/big-design/src/components/Form/Group/spec.tsx
- packages/big-design/src/components/Form/spec.tsx
- packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/spec.tsx
- packages/big-design/src/components/Modal/Modal.tsx
- packages/big-design/src/components/Modal/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Radio/spec.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Textarea/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Textarea/spec.tsx
- packages/big-design/src/utils/uniqueId.ts
- packages/docs/PropTables/FormPropTable.tsx
- packages/docs/PropTables/InputPropTable.tsx
- packages/docs/pages/Checkbox/CheckboxPage.tsx
- packages/docs/pages/Form/FormPage.tsx
- packages/docs/pages/Input/InputPage.tsx
- packages/docs/pages/Radio/RadioPage.tsx
- packages/docs/pages/Select/SelectPage.tsx
- packages/docs/pages/Textarea/TextareaPage.tsx
Convert `Form` to a functional component and remove static members.
---
Use `FormControlError`, `FormControlLabel`, `FormGroup`, and `Fieldset`
instead of `Form.Error`, `Form.Label`, `Form.Group`, and `Form.Fieldset` respectively.
> feat(component): convert Form to FC and remove static members

- packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/styled.tsx
- packages/big-design/src/components/Select/Select.tsx
Inputs with `Icons` are not perfectly aligned and have extra margins / paddings. This PR is an attempt to resolve that, alongside ensuring the whole field upon autocomplete is filled.
> fix(component): icon alignment and autofill input fixes

- packages/big-design/src/components/Box/Box.tsx
- packages/big-design/src/components/Box/spec.tsx
- packages/big-design/src/components/Flex/Flex.tsx
- packages/big-design/src/components/Flex/Item/Item.tsx
- packages/big-design/src/components/Flex/spec.tsx
- packages/big-design/src/components/Grid/Grid.tsx
- packages/big-design/src/components/Grid/spec.tsx
Adds a few missing `forwardRef`s
Example use-case I stumbled upon in my app is needing to scroll to certain elements. Since we don't provide users with the element refs we cannot scroll to them programmatically
> feat(component): add forwardRef to box, flex and grid

- packages/big-design/src/components/Modal/Modal.tsx
- packages/big-design/src/components/Modal/spec.tsx
This change will unmount the modal successfully by deactivating the focus trap allowing other components to listen for events.
> fix(component): unmount Modals appropriately by deactivating focus trap

- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/styled.ts
- packages/big-design/src/components/List/Item/styled.tsx
- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/List/ListPopperElement.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Select/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tooltip/Tooltip.tsx
- packages/big-design/src/hooks/index.ts
- packages/big-design/src/hooks/useIsomorphicLayoutEffect.ts
Fixes `DropdownLinkItems` `a` tag not spanning the width of the element, thus clicks wouldn't work unless clicking the link.
Links now also matches background transitions of `DropdownItems`.
Fix scroll bug by scheduling Popper to update when user resizes window.
> fix(component): fix links in Dropdown items and scroll bug

- README.md
- packages/docs/components/SideNav/SideNavLogo/SideNavLogo.tsx
- packages/docs/pages/GettingStarted/GettingStartedPage.tsx
- packages/docs/pages/_app.tsx
Rename public asset paths.
Documentation says you can now access `public/` files via root path: https://nextjs.org/docs/basic-features/static-file-serving
> fix(docs): rename public asset paths

- packages/examples/tsconfig.json
`tsc` can parse json5 but not CodeSandbox.
> fix(examples): remove danling comma

- packages/big-design/src/components/Badge/Badge.tsx
- packages/big-design/src/components/Badge/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Badge/spec.tsx
- packages/big-design/src/components/Badge/styled.tsx
- packages/docs/PropTables/BadgePropTable.tsx
- packages/docs/pages/Badge/BadgePage.tsx
- Restrict `Badge` component to use label prop.
- Fix styling inconsistencies:
- line-height grew inside `Text` component
- extra 1px space on top
> feat(component): restrict badges to use label props and style fixes

- packages/big-design/src/components/Panel/Panel.tsx
- packages/big-design/src/components/Panel/spec.tsx
- packages/big-design/src/components/Panel/styled.tsx
Fixes this display issue on mobile with `Panels`:
> fix(component): proper panel action button width

- packages/big-design/src/components/StatefulTable/reducer.ts
`selectedItems` were not being re-computed when items changed, a bit of a corner-case scenario since items shouldn't be changing that much.
If an item is selected and removed from `items`, `selectedItems` would still have a reference to it.
Contrived example:
```tsx
export default () => {
const [items, setItems] = React.useState([
{ sku: 'SM13', name: '[Sample] Smith Journal 13', stock: 25 },
{ sku: 'DPB', name: '[Sample] Dustpan & Brush', stock: 34 },
{ sku: 'OFSUC', name: '[Sample] Utility Caddy', stock: 45 },
]);
const [selectedItems, setSelectedItems] = React.useState([]);
const deleteItem = () => {
const [_first, ...rest] = items; 
setItems(rest);
};
return (
<StatefulTable
selectable
columns={[
{ header: 'Sku', hash: 'sku', render: ({ sku }) => sku },
{ header: 'Name', hash: 'name', …
```
> fix(component): compute selectedItems on StatefulTable when items change

- .circleci/config.yml
- yarn.lock
`yarn.lock` got out-of-sync. This change is temporary until we can switch to yarn v2.
Related issues:
- https://github.com/yarnpkg/yarn/issues/5840
- https://github.com/yarnpkg/yarn/pull/6554
Works as expected: https://app.circleci.com/pipelines/github/bigcommerce/big-design/1237/workflows/46371961-c584-44ed-8941-a62d1f6ece08/jobs/1223
> fix(ci): yarn install --frozen-lockfile doesn't error

- packages/big-design/src/components/StatefulTable/StatefulTable.tsx
- packages/big-design/src/components/StatefulTable/reducer.ts
- packages/big-design/src/components/StatefulTable/spec.tsx
- packages/configs/tslint/tslint.json
- packages/docs/PropTables/StatefulTablePropTable.tsx
`StatefulTable` column can now be sorted via `sortKey` or a custom `sortFn`.
> feat(component): stateful table sortFn

- packages/big-design/src/components/Pagination/Pagination.tsx
There was a scenario (totalItems = 0) when `currentPage` was set to `0` instead of `1`.
> fix(component): pagination avoid page 0

- packages/big-design/src/components/Table/HeaderCell/HeaderCell.tsx
- packages/big-design/src/components/Table/HeaderCell/styled.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/types.ts
- packages/docs/PropTables/StatefulTablePropTable.tsx
- packages/docs/PropTables/TablePropTable.tsx
Adds ability to hide individual headers on the `Table` and `Stateful Table` components without hiding all of them.
Manual testing, see screenshot below
> feat(component): CHP-6225 adds ability to hide individual table headers

- packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/Select/spec.tsx
The autocomplete prop will be only set to `no` for Select and MultiSelect components.
Fixes #358
> fix: autocomplete=no only set for Selects

- packages/big-design/package.json
- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/types.ts
- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/types.ts
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/types.ts
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tooltip/Tooltip.tsx
- yarn.lock
Bump dependencies.
Use new APIs for `react-popper`.
> chore: bump react-popper and downshift

- packages/big-design/src/components/Modal/Modal.tsx
Currently, when opening a Modal the modal ref will be focused, changed that so that it will fall back to the modal ref if no other focusable element is present.
> fix(component): modal focus first focusable element

- packages/big-design/src/components/Dropdown/spec.tsx
- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
Sets `selectOptions` when `options` prop updates. Added tests.
Closes #363.
> fix: render new options for Selects when option prop changes

- packages/big-design/src/components/Dropdown/spec.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/docs/pages/Dropdown/DropdownPage.tsx
- packages/docs/pages/MultiSelect/MultiSelectPage.tsx
- packages/docs/pages/Select/SelectPage.tsx
Add extra options to examples since the ones provided were not enough to showcase the `maxHeight` property. I thought it was broken.
Added tests.
> fix: add extra options for maxHeight examples and set up tests

- packages/big-design-theme/src/helpers/helpers.ts
Polished now has a `math` function that simplifies our helper quite a bit. `stripUnit` is also being deprecated and was causing warning logs.
> chore(theme): use polished's math instead of stripUnit

- packages/big-design/src/components/Counter/Counter.tsx
- packages/big-design/src/components/Counter/index.ts
- packages/big-design/src/components/Counter/private.ts
- packages/big-design/src/components/Counter/spec.tsx
- packages/big-design/src/components/Counter/styled.ts
- packages/big-design/src/components/Input/private.ts
- packages/big-design/src/components/Input/styled.tsx
- packages/big-design/src/components/index.ts
- packages/docs/PropTables/CounterPropTable.tsx
- packages/docs/PropTables/InputPropTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/next.config.js
- packages/docs/pages/Counter/CounterPage.tsx
Adds a `Counter` component to the component library 
Manual testing
> feat(component): adds Counter component to bigdesign

- packages/big-design/src/components/MultiSelect/types.ts
- packages/big-design/src/components/Select/types.ts
- packages/docs/PropTables/MultiSelectPropTable.tsx
- packages/docs/PropTables/SelectPropTable.tsx
Add description prop to Select dropdown
We support the description prop, but typescript doesn't recognise it as a prop
Select
MultiSelect
ping @deini @animesh1987 @chanceaclark
> fix(component): SHIPPING-1526 adds description to Select & MultiSelect

- packages/big-design/src/components/Table/DataCell/DataCell.tsx
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/Table/types.ts
- packages/docs/PropTables/StatefulTablePropTable.tsx
- packages/docs/PropTables/TablePropTable.tsx
Change `verticalAlign: 'center'` to `verticalAlign: 'middle'`.
`vertical-align: center;` isn't valid CSS.
> fix(component): table column prop  incorrect value for middle alignment

- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/Table/styled.tsx
- packages/docs/components/PropTable/PropTable.tsx
Remove `margin-bottom` on `TableFigure` components. See breaking change snippet below if margin is needed:
```
Visual breaking change; removes the bottom margin on `TableFigure` components.
Use the built in `margin` props if margin is needed.
```
> fix(component): remove bottom margin on the TableFigure component

- packages/big-design/package.json
- packages/big-design/src/components/Select/Select.tsx
- yarn.lock
Bump downshift. 
Set highlightedIndex to `-1` when needed to prevent the option from selecting when blurring out of the component.
Fixes #393
> fix(component): prevent select from selecting option when blurring

- packages/big-design/package.json
- packages/big-design/src/components/Select/spec.tsx
- yarn.lock
This will fix the weird behavior of Selects until we can properly figure out why it breaks using the latest versions of Downshift.
The issue is that our `onOptionChange` is being called two times when you click an option, which trigger an infinite loop effect. By expecting a single call we know the code is working as expected.
Tested locally as well.
Fixes #396
> fix: lock downshift to 5.2.0 to fix behavior of onOptionChange

- packages/big-design/package.json
- yarn.lock
Bump Downshift to 5.2.2 since it was the latest version we had before the issues.
> chore: bump downshift to 5.2.2

- packages/big-design/src/components/Button/Button.tsx
- packages/big-design/src/components/ProgressCircle/ProgressCircle.tsx
- packages/big-design/src/components/ProgressCircle/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/ProgressCircle/constants.ts
- packages/big-design/src/components/ProgressCircle/spec.tsx
- packages/docs/PropTables/ProgressCirclePropTable.tsx
Adds a new size for the `ProgressCircle` component. New size is 24px x 24px which we needed to shift the `xSmall` size down to `xxSmall`.
This is in order to have a loading icon for the `Tree` component in #406.
```
`xSmall` `ProgressCircle` size changed to `xxSmall`.
```
> feat(component): add additional size to ProgressCircle component

- .github/CODEOWNERS
Sets the @bigcommerce/frontend team as CODEOWNERS for `big-design`.
An ongoing effort to get BigCommerce employees insight and more involved with `big-design`. Also, the previous method of having SMEs as CODEOWNERS can restrict merging if someone is on PTO.
> chore: set frontend team as codeowners

- packages/docs/PropTables/FlexPropTable.tsx
- packages/docs/pages/Message/MessagePage.tsx
Found this typo while browsing BigDesign site.
> fix: typo in description text

- packages/docs/PropTables/LinkPropTable.tsx
Proposed fix for grammar issue in `external` description on [Link props page](https://developer.bigcommerce.com/big-design/link).
> fix(docs): grammar update

- packages/big-design/src/managers/alerts/manager.ts
- packages/big-design/src/managers/alerts/spec.tsx
- packages/docs/MethodLists/AlertsManagerMethodLists.tsx
- packages/docs/pages/Alert/AlertPage.tsx
Currently, there is no easy way to clear all alerts. This PR adds a `clear` method to the alert manager. An example usage would be calling this method from a router's `change` event.
> feat(component): add clear method to alerts manager

- packages/big-design/src/managers/alerts/manager.ts
- packages/big-design/src/managers/alerts/spec.tsx
- packages/docs/MethodLists/AlertsManagerMethodLists.tsx
- packages/docs/PropTables/AlertPropTable.tsx
Auto-dismiss an alert using AlertManager after 5s
Eg usage:
```js
alertsManager.add({ title: 'Hello', fadeAway: true });
```
> feat(component): add fadeAway option to alertsManager

- packages/docs/components/NextLink/NextLink.tsx
Links to `ids` were getting overridden by production's `URL_PREFIX`
> fix(docs): fix hash routes

- packages/big-design/src/components/List/Item/CheckboxItem.tsx
- packages/big-design/src/components/List/Item/styled.tsx
- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/big-design/src/components/Select/types.ts
- packages/docs/PropTables/SelectPropTable.tsx
- packages/docs/pages/MultiSelect/MultiSelectPage.tsx
- packages/docs/pages/Select/SelectPage.tsx
Adding a description to the `select option` and `select action`.
Unit tests.
> feat(component): add description to select option and select action

- packages/docs/components/SideNav/SideNavLogo/SideNavLogo.tsx
- packages/docs/components/SideNav/SideNavLogo/styled.tsx
- packages/docs/next.config.js
Adds the current BigDesign version in the docs.
Closes #394.
> feat(docs): add BigDesign version on the documentation site

- packages/big-design/src/components/Popover/Popover.tsx
- packages/big-design/src/components/Popover/index.ts
- packages/big-design/src/components/Popover/spec.tsx
- packages/big-design/src/components/index.ts
- packages/docs/PropTables/PopoverPropTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/next.config.js
- packages/docs/pages/Popover/PopoverPage.tsx
Adds `Popover` component. This is a util component that will help facilitate building other components such as the advanced table filters and search components.
> feat(component): add Popover component

- packages/big-design-theme/README.md
- packages/big-design-theme/src/index.ts
Adds the `ThemeInterface` to `styled-components` `DefaultTheme` type so repositories don't have to manually include them.
Assumes you wrap your app in a `ThemeProvider` and added documentation on how to add that.
> feat(theme): add DefaultTheme extension types

- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/spec.tsx
- packages/big-design/src/components/Dropdown/types.ts
- packages/docs/PropTables/DropdownPropTable.tsx
Allows `DropdownItemGroup`'s to have optional `label` key/vals.
> fix(component): allow Dropdown groups to have optional `label`

- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/spec.tsx
- packages/big-design/src/components/Dropdown/types.ts
- packages/big-design/src/components/List/GroupSeparator/ListGroupSeparator.tsx
- packages/big-design/src/components/List/GroupSeparator/index.ts
- packages/docs/PropTables/DropdownPropTable.tsx
Add hr to dropdown when separated flag is true for dropdown groups
> feat(component): add separator to dropdown item groups

- packages/big-design/src/components/Modal/Modal.tsx
- packages/big-design/src/components/Modal/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Modal/spec.tsx
Fixes a corner case of `overflowY` not being set back to its initial value when unmounting the modal.
Eg:
```jsx
{isOpen && <Modal isOpen={true} />}
```
In this scenario, setting `isOpen` to false won't run the expected cleanups.
Did a bit of refactoring by creating an `InternalModal` which we mount/unmount on `isOpen`, this simplifies our effects as we don't need to check for `isOpen` in our cleanup effects.
> fix(component): modal overflowY cleanup on unmount

- packages/big-design/src/components/Popover/Popover.tsx
- packages/big-design/src/components/Tooltip/Tooltip.tsx
- packages/docs/PropTables/PopoverPropTable.tsx
- Make Popover and Tooltips have the same default offset as dropdowns. 
- Rename offset props for Popover
> feat(component): rename popover offset props and defaults

- packages/big-design/src/components/Tree/Tree.tsx
- packages/big-design/src/components/Tree/TreeNode/TreeNode.tsx
- packages/big-design/src/components/Tree/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tree/spec.tsx
- packages/big-design/src/components/Tree/types.ts
Adds id support to the `Tree` component.
ID schema:
```
// TreeId
id || `bd-tree-{uniqueId}`
// TreeNodeId
`{treeId}-treenode-{nodeId}`
```
> feat(component): add id support for Tree component

- packages/big-design/src/components/Checkbox/Checkbox.tsx
- packages/big-design/src/components/Checkbox/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
Adds `aria-checked` to the hidden `input[type="checkbox"]` to display state change.
> feat(component): add aria-checked to Checkbox component

- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Input/spec.tsx
- packages/big-design/src/components/Textarea/Textarea.tsx
- packages/big-design/src/components/Textarea/spec.tsx
Fixing the error state of the `Input` and `Textarea` components.
Cases when we don't show error state:
- Empty array;
- When we get an empty `error` array after firing `validationError` in the case when we receive error property as an `array` or an `array` with the "invalid" elements.
- Existing unit tests;
- Tested locally.
ping @chanceaclark
> fix(component): form controls error states

- packages/big-design/src/utils/localizationProvider/localizationProvider.ts
Fixes issue in Datepicker as to how days row is setup. 
ping @bigcommerce/frontend @chanceaclark
> fix(datepicker): fix order of days displayed

- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/List/styled.tsx
- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
Open list when Select is clicked. Visually hide the list when select is closed.
Should fix #459 & fix #460. I was, however, unable to reproduce #459 but I'm hoping these changes fix it.
> fix: open select when clicked and visually hide list

- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
Dropdown's `<List />` component was missing the `isOpen` prop.
Will lurk the `Downshift` library to figure out why `getMenuProps` returns `any`, which caused an oversight by me thinking `ts` would catch an issue like this.
> fix(component): add missing prop to open dropdown

- packages/big-design/src/components/Radio/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Radio/styled.tsx
- packages/big-design/src/components/Tree/__snapshots__/spec.tsx.snap
Fixing on the radio button. A content might shrink the radio button on different screens.
**Before:**
**After:**
Tested locally.
ping @golcinho @chanceaclark
> fix(component): do not shrink the radio button

- packages/docs/pages/Alert/AlertPage.tsx
Slightly changed docs for `Alerts` page.
Added some information regarding how to use `createAlertsManager` instance:
Changed code in `CodeSnippet` to be string, as it didn't render correctly, in was rendering extra `}` character, which could confuse consumers of this example:
> fix(docs): alert docs - alert management import clarification

- packages/big-design-theme/src/helpers/helpers.ts
- packages/big-design-theme/src/helpers/index.ts
- packages/big-design/src/components/Button/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/ProgressCircle/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/ProgressCircle/styled.tsx
Per title - progress circle crashes due to `rem` in Safari 14 - updated to use `em`, per MDN docs, created `emCalc` utility per 'offline' suggestion by @deini .
> fix(component): updates progress circle to use em instead of rem due to error in Safari 14

- packages/docs/pages/Table/TablePage.tsx
Adds documentation to the `Table` page for the `TableFigure` component currently exposed in BD
> feat(component): adds documentation for the TableFigure component

- packages/docs/pages/Switch/SwitchPage.tsx
Updates `Switch` documentation to state that this component is for immediate "toggle" changes and is thus not appropriate for use in submittable forms. Removes `Form` from code example, replaces with `Box` - background changes color for visual representation of component usage, but I'm happy to use better examples.
> docs(component): updates switch docs not for use in forms

- packages/docs/pages/_document.tsx
```
@bigcommerce/docs: warn  - Your custom Document (pages/_document) did not render all the required subcomponent.
@bigcommerce/docs: Missing component: <Html />
@bigcommerce/docs: Read how to fix here: https://err.sh/next.js/missing-document-component
```
https://github.com/vercel/next.js/blob/master/errors/missing-document-component.md
> fix(docs): add missing Html component to document

- packages/big-design/src/components/StatefulTable/spec.tsx
- packages/big-design/src/components/Table/Actions/Actions.tsx
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/Table/types.ts
- packages/docs/PropTables/StatefulTablePropTable.tsx
- packages/docs/PropTables/TablePropTable.tsx
Fixes issue of re-rendering custom table actions.
Repro: https://codesandbox.io/s/priceless-hill-dus8q?file=/src/App.tsx  (type on the input)
Table and StatefulTable `actions` prop changed from expecint a
React.ComponentType to React.ReactNode.
Old:
```jsx
<Table actions={() => <Button>Some Action</Button>} />
```
New:
```jsx
<Table actions={<Button>Some Action</Button>} />
```
> feat(component): use ReactNode for table actions

- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
Ensure autocomplete works on Select component. 
The Select component is currently using `autoComplete: 'no'`, when it should be `autoComplete: 'off'`.
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
> fix(component): ensure autocomplete works on Select component

- packages/big-design/src/components/StatefulTree/hooks/useSelectable.ts
When `defaultSelected` prop changes, the `selectedValues` state didn't update.
This fixes the issue outlined in #488.
Fixes #488.
> fix(component): selected values were not matching state

- README.md
- packages/big-design-icons/README.md
- packages/big-design-theme/README.md
- packages/big-design/README.md
- packages/docs/pages/GettingStarted/GettingStartedPage.tsx
Add version number for `styled-components` in the README.md
Currently `npm install styled-components` will install version 5. We depend on version 4.
@bigcommerce/frontend
> fix(docs): Specify styled-components version in the README

- .circleci/config.yml
- .eslintrc.js
- package.json
- packages/big-design/src/components/Switch/styled.tsx
- packages/big-design/src/components/Typography/styled.tsx
- packages/docs/pages/Collapse/CollapsePage.tsx
We currently rely on Husky (git-hook) to run `eslint`. Just noticed we have a few eslint issues, probably from users who skip the git-hook. 
This change runs eslint on ci. We have a single `job` in our `workflow`. I'll open a different PR to split it up.
> chore(ci): run eslint on ci

- packages/big-design/src/components/StatefulTable/StatefulTable.tsx
- packages/big-design/src/components/StatefulTable/spec.tsx
- packages/docs/PropTables/StatefulTablePropTable.tsx
- packages/docs/PropTables/TablePropTable.tsx
- packages/docs/pages/StatefulTable/StatefulTablePage.tsx
- packages/docs/pages/Table/TablePage.tsx
Add drag and drop support to `StatefulTable` component.
[Feature request for Drag and Drop](https://github.com/bigcommerce/big-design/issues/426)
Closes #426.
ping @bigcommerce/frontend @deini @chanceaclark
> feat(component): Add drag and drop support to stateful table component

- packages/big-design/src/components/Alert/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Button/Button.tsx
- packages/big-design/src/components/Button/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Chip/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/InlineMessage/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Message/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Modal/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
Removes the `tabIndex` and `role` props from `Button` components.
`<button>` elements already have a default `tabindex="0"` and `role="button"` applied to them via the user-agent. These are unnecessary and can be omitted.
> fix(component): remove tabindex and role from Button

- packages/big-design/src/components/Datepicker/Datepicker.tsx
Adds `disabled` prop support to Datepicker.
Passing `disabled` into the `customInput` isn't supported by the library.
[Docs](https://reactdatepicker.com/#example-disable-datepicker) require you to pass `disabled` into the HOC.
> fix(component): add disabled support to Datepicker

- packages/big-design/src/components/Panel/Panel.tsx
- packages/big-design/src/components/Panel/spec.tsx
- packages/docs/PropTables/PanelPropTable.tsx
Adds `headerId` as a prop to `Panel` components.
Gives users the ability to add an `id` attribute to the heading. Useful in situation where you want to use URL hashes to link to `Panel` headings, en lieu of using the `id` on the `Panel` itself.
> feat(component): add headerId prop to Panel

- packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/styled.tsx
> fix(component): prevent autofill overflow on Inputs

- packages/big-design/src/components/Pagination/Pagination.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
Sets dropdown on the `Pagination` component to fixed position.
Fixes #401 
Wrapped a `StatefulTable` in a `TableFigure` component for quick testing.
> fix(component): set fixed position for dropdown in pagination

- packages/big-design/src/components/Stepper/Step/Step.tsx
- packages/big-design/src/components/Stepper/Step/index.ts
- packages/big-design/src/components/Stepper/Step/styled.tsx
- packages/big-design/src/components/Stepper/Stepper.tsx
- packages/big-design/src/components/Stepper/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Stepper/index.ts
- packages/big-design/src/components/Stepper/spec.tsx
- packages/big-design/src/components/index.ts
- packages/docs/PropTables/StepperPropTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/next.config.js
- packages/docs/pages/Stepper/StepperPage.tsx
Adds the Stepper component, a new component to track progress on multi-step tasks.
[Feature request for a Stepper component](https://github.com/bigcommerce/big-design/issues/420)
> feat(component): add Stepper component

- packages/docs/PropTables/DropdownPropTable.tsx
Renaming `options` to `items` in the `DropdownItemGroup` doc section.
`DropdownItemGroup` interface:
**Prev view:**
**Next view:**
ping @bigcommerce/frontend
> fix(docs): dropdown doc fix

- packages/big-design/src/components/PillTabs/PillTabs.tsx
- packages/big-design/src/components/PillTabs/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/PillTabs/index.ts
- packages/big-design/src/components/PillTabs/spec.tsx
- packages/big-design/src/components/PillTabs/styled.tsx
- packages/big-design/src/components/StatefulTable/StatefulTable.tsx
- packages/big-design/src/components/StatefulTable/reducer.ts
- packages/big-design/src/components/StatefulTable/spec.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/Table/types.ts
- packages/big-design/src/components/index.ts
- packages/big-design/src/hooks/index.ts
- packages/big-design/src/hooks/useWindowResizeListener.ts
- packages/big-design/src/hooks/useWindowSize.ts
- packages/docs/PropTables/PillTabsPropTable.tsx
- packages/docs/PropTables/StatefulTablePropTable.tsx
- packages/docs/PropTables/TablePropTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/next.config.js
- packages/docs/pages/PillTabs/PillTabsPage.tsx
- packages/docs/pages/StatefulTable/StatefulTablePage.tsx
- packages/docs/pages/Table/TablePage.tsx
- packages/docs/pages/_app.tsx
Adds the Pill Tabs component
This component is meant to be a collection of "Views" that are presented as a group of buttons on the top of a Panel. These "Views" act on a collection of items. Tables and Stateful Tables are prime usecases for filterable items that can be used with the Pill Tabs component. Other usecases outside of tables exist, such as an "App Marketplace" or such, a collection of "cards" inside a panel that could also benefit from Pill Tabs
Because of its prime usage with Tables, I have integrated the component as a prop in both the `Table` and the `StatefulTable`. 
**Raw usage:**
Because the `Pill Tabs` can also exist outside tables, a raw `PillTabs` component is exposed
**For the case of `Table`:**
- New Props `filters?` allows for a `PillTabsProps` object to be provided …
> feat(component): add Pill Tabs component

- packages/big-design/src/components/Worksheet/Worksheet.tsx
- packages/big-design/src/components/Worksheet/editors/TextEditor/styled.ts
- packages/big-design/src/components/Worksheet/spec.tsx
- packages/big-design/src/components/Worksheet/types.ts
- packages/big-design/src/components/Worksheet/utils.ts
Changed the API to return the items modified and not just a `cell` object, which in hindsight shouldn't be exposed to the user.
This is a byproduct of thinking of how to implement the `modal` column type.
When an item is changed, `onChange` is now called with an array of items edited.
```
[
{
id: 7,
productName: 'Variant',
visibleOnStorefront: false,
otherField: 'Text',
otherField2: 'leather',
otherField3: 'Field',
numberField: 80,
},
{
id: 1,
productName: 'Shoes Name Three',
visibleOnStorefront: false,
otherField: 'Text',
otherField2: 'cloth',
otherField3: 'Field',
numberField: 50,
},
]
```
For errors, it returns an array of objects with the item and the fields that didn't pass validation for that item.
```
[
{
item: {
id: 5,
productName: '',
visibleOnStorefront: true,
otherField: …
```
> refactor(component): return items on handlers

- packages/big-design/src/components/Popover/Popover.tsx
Fixes #519
Event click delegation was running when the `Popover` component mounted, causing the `closeOnClickOutside` effect to run.
The idea is to let the anchor elements `onClick` handler take precedence over `closeOnClickOutside`.
https://user-images.githubusercontent.com/10539418/116724117-e022b100-a9a5-11eb-9f4c-c037957ba3e0.mov
> fix(component): add element check to popover closeOnClickOutside effect

- packages/big-design-theme/jest.config.js
- packages/big-design-theme/package.json
- packages/big-design-theme/src/helpers/helpers.spec.ts
- packages/big-design-theme/src/options/options.spec.ts
- packages/big-design/jest.config.js
- packages/big-design/package.json
- packages/configs/jest/jest.config.js
- packages/configs/jest/package.json
- Combines the jest configs into a unified config.
- Sets initial test coverage
- Add some more tests to the theme.
Let's us make sure our components are covered.
See the CI run.
> chore(configs): combine jest configs and set initial test coverage

- packages/big-design/src/components/Worksheet/Cell/Cell.tsx
- packages/big-design/src/components/Worksheet/Row/Row.tsx
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/editors/ModalEditor/ModalEditor.tsx
- packages/big-design/src/components/Worksheet/spec.tsx
- packages/big-design/src/components/Worksheet/types.ts
Allow the Text, Number, and Modal column types to be formatted.
Allow custom text readability.
```
{
hash: 'numberField',
header: 'Number field',
type: 'number',
validation: (value: number) => value >= 50,
formatting: (value: number) => `$${value}.00`,
},
```
> feat(component): allow formatting of columns

- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/types.ts
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/types.ts
- packages/docs/PropTables/MultiSelectPropTable.tsx
- packages/docs/PropTables/SelectPropTable.tsx
Allow custom values for autoComplete. Defaults to `off`.
Fixes #540
> feat(component): add autoComplete prop for selects

- .github/CODEOWNERS
Adds the @bigcommerce/product-design team as codeowners.
The @bigcommerce/product-design team wants to have more insight on additions/changes from external contributions. Adding the team on all PR's will give more visibility on all development.
**Note: We are still requiring a member of @bigcommerce/frontend team to approve before merging code.**
cc. @valterfatia @eugene-polev
> chore: add @bigcommerce/product-design to codeowners

- packages/big-design/src/components/Modal/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Modal/styled.tsx
Change Modal to center its content with `justify-content` and `align-items` instead of `transform`
`transform: translate` messes with drag-n-drop preview positioning
Modal
Dialog
Manually tested on Google Chrome v91.0.4472.77 on MacOS by viewing how Modal component looks and behaves on different viewport sizes.
> fix(component): change positioning of Modal

- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/MultiSelect/types.ts
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/big-design/src/components/Select/types.ts
- packages/docs/PropTables/MultiSelectPropTable.tsx
- packages/docs/PropTables/SelectPropTable.tsx
Add `onOpen` and `onClose` props to Selects.
For some interactions on the Worksheet component (and other uses), I need to know when the dropdown has been opened or closed.
Unit tests and locally
> feat(component): add onOpen and onClose to Selects

- packages/big-design/package.json
- packages/big-design/src/components/Worksheet/Worksheet.tsx
- packages/big-design/src/components/Worksheet/index.ts
- packages/big-design/src/components/Worksheet/types.ts
- packages/big-design/src/components/index.ts
- yarn.lock
- Updates `react-beautiful-dnd` for `react@17` support.
- Exposes the `Worksheet` component for a alpha release.
Some consumers couldn't fully update to `react@17`.
ping @bigcommerce/frontend
> chore(deps): update react-beautiful-dnd for react@17 support

- packages/big-design/src/components/Tooltip/Tooltip.tsx
- packages/big-design/src/components/Tooltip/spec.tsx
Passes the `id` prop to the Tooltip wrapper.
Missing functionality that should have been there.
Added unit tests and testing manually in the browser.
> feat(component): pass id to Tooltip wrapper

- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
Handle the `required` attribute we add to the input in MultiSelect, by removing it when a selection has been made.
Fixes #524.
Added unit tests. In addition, I locally tested this with `react-final-form` and natively to make sure validation is still being handled correctly.
> fix(component): handle required attribute in MultiSelects

- packages/big-design/jest.config.js
- packages/big-design/src/components/Search/Search.tsx
- packages/big-design/src/components/Search/index.ts
- packages/big-design/src/components/Search/spec.tsx
- packages/big-design/src/components/Search/types.ts
- packages/big-design/src/components/StatefulTable/StatefulTable.tsx
- packages/big-design/src/components/Table/Search/index.ts
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/Table/types.ts
- packages/big-design/src/components/index.ts
- packages/docs/PropTables/SearchPropTable.tsx
- packages/docs/PropTables/TablePropTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/next.config.js
- packages/docs/pages/Search/SearchPage.tsx
- packages/docs/pages/Table/TablePage.tsx
Moves the `Search` component into its own exposed component and removes it from the `Table` component.
TL'DR: The `search` prop wasn't actually being used when we exposed it in the alpha version.
We found while implementing search patterns, that it's easier to compose the UI with compositional components instead of prebuilt UIs. Examposing it in the alpha version gave us some insight in this matter. Also, extracting it out of the `Table` component will allow us to extend this component in the future.
- I migrated the existing tests over from the `Table` tests.
- Also, tested performance on the `StatefulTable` and it's still good.
> feat(component): move Search into its own exposed component

- packages/big-design/src/components/StatefulTable/StatefulTable.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/Table/types.ts
- packages/docs/PropTables/TablePropTable.tsx
- packages/docs/pages/Table/TablePage.tsx
Removes the `filters` prop from the `Table` component.
Similar to #557; it's better as a compositional component rather than apart of the `Table` component. Still apart of `StatefulTable`.
N/A
Removed unit tests and ensure they worked correctly for the `StatefulTable`.
> chore(component): remove filters prop from Table component

- packages/big-design/src/components/ButtonGroup/ButtonGroup.tsx
Update `actionsState ` on every `actions` prop change for avoiding wrong behavior with callbacks.
The component doesn't re-render on props change.
before:
https://user-images.githubusercontent.com/9980803/125099509-c22da700-e0e0-11eb-964a-cda9326876af.mov
after:
https://user-images.githubusercontent.com/9980803/125099562-cfe32c80-e0e0-11eb-850d-ee425459c573.mov
Locally
ping @chanceaclark
> fix(component): fix button group state

- packages/big-design/src/components/Worksheet/Cell/Cell.tsx
- packages/big-design/src/components/Worksheet/Row/Row.tsx
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/editors/CheckboxEditor/CheckboxEditor.tsx
- packages/big-design/src/components/Worksheet/editors/ModalEditor/ModalEditor.tsx
- packages/big-design/src/components/Worksheet/editors/SelectEditor/SelectEditor.tsx
- packages/big-design/src/components/Worksheet/editors/SelectEditor/styled.ts
- packages/big-design/src/components/Worksheet/hooks/useEditableCell/useEditableCell.ts
- packages/big-design/src/components/Worksheet/hooks/useKeyEvents/useKeyEvents.ts
- packages/big-design/src/components/Worksheet/hooks/useNavigation/useNavigation.ts
- packages/big-design/src/components/Worksheet/spec.tsx
- packages/big-design/src/components/Worksheet/types.ts
- packages/docs/PropTables/WorksheetPropTable.tsx
- packages/docs/pages/Worksheet/WorksheetPage.tsx
Add the `disabled` prop for all column types in Worksheet.
For the scenarios when a column is only used to display a static value.
Locally. Unit tests.
> feat(component): add the option to disable columns in Worksheet

- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/spec.tsx
Limit the tests running a Worksheet with selectable columns.
Adding a `Select` to the component requires for the test to `await` for the component to be ready. This adds time to the runtime of the test. By limiting these instances to only necessary tests, we get a faster turnaround.
Before:
After:
> refactor: split selectable columns from tests

- packages/big-design/src/components/MultiSelect/spec.tsx
Update the `MultiSelect` tests to perform a bit faster. We were getting a bunch of timeout issues on the `MultiSelect` tests.
**Before:**
```bash
@bigcommerce/big-design: PASS src/components/MultiSelect/spec.tsx (47.642s)
```
**After:**
```bash
@bigcommerce/big-design: PASS src/components/MultiSelect/spec.tsx (19.414s)
```
> test(component): update MultiSelect tests to have less timeouts

- packages/big-design/src/components/Dropdown/spec.tsx
Refactor Dropdown tests
To decrease timeouts much like in #568 and #567.
Before:
`PASS  src/components/Dropdown/spec.tsx (26.21s)`
After:
`PASS  src/components/Dropdown/spec.tsx (10.043s)`
(This is pre SC v5)
> test(component): update Dropdown tests to have less timeouts

- packages/big-design/src/components/Form/Form.tsx
- packages/big-design/src/components/Form/spec.tsx
- packages/big-design/src/components/Form/styled.tsx
- packages/docs/pages/Form/FormPage.tsx
Adds `margin` props to the `Form` component.
I noticed a ton of cases where people need to add margin to a `Form`, for example in a `Modal`. Most cases looked like this:
```tsx
<Box marginBottom="medium">
<Form>
{...}
</Form>
</Box>
```
This aims to make the DX better, so we can do this:
```tsx
<Form marginBottom="medium" />
```
> feat(component): add margin props to Form component

- packages/big-design-theme/src/helpers/helpers.spec.ts
- packages/big-design-theme/src/helpers/helpers.ts
- packages/big-design-theme/src/helpers/index.ts
Provides a `listReset` helper on the theme.
There have been a few use-cases where we want to build a list of components. In order to do that semantically you need a `ul/ol` with reset styles. This utility should help prevent writing the following repeatedly:
```tsx
const StyledUl = styled.ul`
list-style-type: none;
margin: 0;
padding: 0;
`;
```
Now you can writing it like so:
```tsx
const StyledUl = styled.ul`
$({ theme } => theme.helpers.listReset);
`;
```
> feat(theme): add listReset helper

- packages/big-design/src/managers/alerts/manager.ts
- packages/big-design/src/managers/alerts/spec.tsx
- packages/big-design/src/managers/alerts/types.ts
- packages/big-design/src/utils/messagingHelpers.tsx
Fixes the alert manager auto-dismissing hidden alerts.
The `setTimeout` was being invoked as soon as the alert was created, which meant that the alert was already counting down to 0 before you even saw it.
https://user-images.githubusercontent.com/10539418/129981438-ece33b9a-a859-4ea5-8346-4bf1bfd95bfb.mov
Added additional test for it.
shoutout to @jordan-massingill for catching this
> fix(component): alert autoDismiss firing when not visible

- packages/big-design/src/components/Counter/Counter.tsx
- packages/big-design/src/components/Counter/spec.tsx
- packages/big-design/src/components/Form/Group/Group.tsx
- packages/big-design/src/components/Form/Group/spec.tsx
- packages/big-design/src/components/Form/useInputErrors.ts
- packages/big-design/src/components/Input/Input.tsx
- packages/big-design/src/components/Textarea/Textarea.tsx
Fix input errors not showing when not a direct child of `<FormGroup>`
Refactored how `FormGroup` handles children errors from `Input`, `Counter`, and `TextArea`. Currently, `FormGroup` relies on `Input` to be an immediate child. This is an issue for some form libraries, eg. FinalForm's `Field` component.
```jsx
<FormGroup>
<Field name="name">
{({ input, meta }) => (
<Input
error={meta.error}
label="Name"
required
{...input}
/>
)}
</Field>
</FormGroup>
```
> fix(component): input errors now showing when nested

- packages/docs/next.config.js
Fixes the logs happening on the `docs` package.
```
Critical dependency: the request of a dependency is an expression
```
This PR makes webpack not parse `@babel/standalone`.
> fix(docs): dependency is an expression

- packages/big-design-icons/package.json
- packages/big-design-icons/scripts/build-flags.js
- packages/big-design-icons/scripts/build.js
- yarn.lock
Really simple promise pool for icon processing.
The previous solution will throw all icons at once, this makes the log print the list of icons and then hang for 11s until they are all processed. This commit just implements a really simple promise-pool to process them based on the number of available cpus.
<table>
<tr>
<td>Before
<td>After
<tr>
<td><video src="https://user-images.githubusercontent.com/4542735/133357407-8cd31bef-a212-4d66-a721-ec1ff3a5ed4b.mov" />
<td><video src="https://user-images.githubusercontent.com/4542735/133357409-f3cacde3-5286-4bc2-a6e6-ee79835fbc9a.mov" />
</table>
I ran the command locally and it works correctly.
> chore(icons): Process icons based on the number of available CPUs

- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
Hides pills close buttons in `MultiSelect` when it is disabled.
We don't want these to be modified when the select is disabled.
Added unit tests for this.
Fixes #587.
> fix(component): hide close buttons in MultiSelect

- packages/big-design-icons/package.json
- packages/big-design-theme/package.json
- packages/big-design/package.json
- packages/configs/babel/babel.config.js
- yarn.lock
Update babel browserslist and remove unused babel plugins.
- Default preset env is doing extra work to support browsers we no longer support.
- Forgot to remove the plugins on a previous PRs
- This should reduce bundle size, I'll pull up some numbers.
> chore(configs): update babel browserslist

- packages/docs/pages/Spacing/SpacingPage.tsx
Rename "Props" tab on "Spacing" page to "Spacing values".
"Spacing values" name better reflects the content of the tab.
Manually tested. Functionality shouldn't have changed.
> chore(docs): rename spacing values tab

- packages/big-design/src/components/PillTabs/PillTabs.tsx
- packages/big-design/src/components/PillTabs/__snapshots__/spec.tsx.snap
Change right margin of the PillTab from xLarge/24px/1.5rem to xSmall/8px/0.5rem
According to BigDesign figma.
https://www.figma.com/file/duwtpbP2tnLLQQmAkwtrNC/BigDesign-Lib?node-id=6093%3A16205
Manually tested. Functionality shouldn't have changed.
> fix(component): fix PillTab margin

- .circleci/config.yml
Updated the CircleCI `node` orb version to the latest.
Older version CA cert for curl commands was invalid.
N/A
[**Issue CI build**](https://app.circleci.com/pipelines/github/bigcommerce/big-design/2284/workflows/1738e767-015e-4f0f-811a-df61fcea78dd/jobs/2214/parallel-runs/0/steps/0-102)
See CI job.
> chore: bump circle-node orb

- packages/docs/components/ContentRoutingTabs/ContentRoutingTabs.tsx
- packages/docs/components/ContentRoutingTabs/index.ts
- packages/docs/components/ContentRoutingTabs/types.ts
- packages/docs/components/ContentRoutingTabs/useContentRoutingTabs.ts
- packages/docs/components/PropTable/PropTable.tsx
- packages/docs/components/index.tsx
- packages/docs/pages/badge.tsx
- Adds `ContentRoutingTabs` component. (Let me know if you have a better suggestion for the name)
- Uses new layout for the `Badge` page.
We wanted to tackle some of the feedback we received when we updated the documentation site in version `0.30.0`.
**Full page:**
**New component with usage:**
https://user-images.githubusercontent.com/10539418/135528437-651a3837-d28d-475c-be93-19ca8115d78c.mov
> feat(docs): update page navigation for Badge documentation

- packages/docs/PropTables/StatefulTablePropTable.tsx
- packages/docs/components/NextLink/NextLink.tsx
- packages/docs/pages/statefulTable.tsx
Updates the `StatefulTable` documentation to use the new layout.
Better navigation.
N/A
> feat(docs): update stateful table page to use new layout

- packages/docs/PropTables/CheckboxPropTable.tsx
- packages/docs/pages/checkbox.tsx
Update Checkbox page to use new layout.
N/A
> feat(docs): update checkbox page to use new layout

- packages/docs/PropTables/shared.tsx
- packages/docs/pages/inline-message.tsx
Update InlineMessage page to use new layout.
N/A
> feat(docs): update inlinemessage page to use new layout

- packages/docs/pages/textarea.tsx
Update textarea to use new page layout.
N/A
> feat(docs): update textarea page to use new layout

- packages/big-design/src/components/Chip/spec.tsx
This PR is aimed to refactor Chip component's tests according to best practices. We take into account recommendations from  Kent C. Dodds [article](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-container-to-query-for-elements). For instance, using `container` for  `query`-ing elements has been removed. Instead,  we replace it with `screen`. 
the changes are based on GitHub [issue](https://github.com/bigcommerce/big-design/issues/635) and PRs will be open for each component separately.
The tests have been successfully run locally.
> test(component): refactor Chip component tests

- packages/big-design/package.json
- packages/big-design/src/components/Datepicker/Datepicker.tsx
- packages/big-design/src/components/Datepicker/spec.tsx
- packages/big-design/src/utils/localizationProvider/localizationProvider.ts
- yarn.lock
Fix `Uncaught RangeError: locale must contain match property` in issue #525  by using `match` from `date-fns`
There is a missing property `match` 
demo: https://take.ms/DCJRv
The change is covered with unit-test to make sure the component still working as expected
> fix(component): Error locale must match

- packages/docs/components/Code/styled.tsx
- packages/docs/pages/breakpoints.tsx
Update Breakpoints page to use new layout.
N/A
> feat(docs): update breakpoints page to use new layout

- packages/big-design/src/components/Search/Search.tsx
- packages/big-design/src/components/Search/spec.tsx
- packages/big-design/src/components/Search/types.ts
- packages/docs/PropTables/SearchPropTable.tsx
- Adds a11y and i18n improvements for `Search` component.
- Adds `autoComplete="off"` as default for `Search` input field. Fixes #580
- Enable UI's to be able to translate the `placeholder` and `aria-*` fields.
- Enable developers to add `aria-*` or other `input` related attributes.
- Disable, by default, the `autoComplete` attribute.
Added tests
> feat(component): Search component improvements.

- packages/big-design/src/components/Box/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Box/spec.tsx
This PR is aimed to refactor Box component's tests according to best practices. We take into account recommendations from  Kent C. Dodds [article](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-container-to-query-for-elements). For instance, using `container` for  `query`-ing elements has been removed. Instead,  we replace it with `screen`. 
the changes are based on GitHub [issue](https://github.com/bigcommerce/big-design/issues/635) and PRs will be open for each component separately.
The tests have been successfully run locally.
> test(component): refactor Box component tests

- packages/docs/pages/form.tsx
Update the `Form` page to use the new documentation layout.
> feat(docs): update form page to use new layout

- packages/docs/pages/display.tsx
Updates the `Display` page to use new documentation layout.
> feat(docs): update display page to use new layout

- README.md
Updates the link to the Lerna website in the README.md to use https://lerna.js.org (official Lerna website).
The existing link in the README.js goes to https://lernajs.io/ which is some kind of spam site.
> Update Lerna JS project link in README.md to correct website.

- packages/docs/pages/button.tsx
- packages/docs/pages/link.tsx
Update Link documentation page to use the new layout
> feat(docs): Update Link documentation page to use new layout

- packages/docs/pages/button.tsx
- packages/docs/pages/modal.tsx
Modal page:
- Add `do and don'ts` section in the modal page to use new layout
- Add keys to fragments to show the corresponding code inside the code editor.
Button page:
- Update button page to add some `<Code primary></Code>` tags.
Modal page:
Button page:
https://user-images.githubusercontent.com/39739180/153637373-1ea349bb-02cd-44d1-b7e5-8d0cf67eb0a8.mp4
> feat(docs): Update modal page to use new layout

- packages/docs/pages/panel.tsx
Add Do's and Don'ts section in Panel documentation page.
> feat(docs): add do and dont section in Panel documentation page

- packages/big-design/src/components/Flex/types.ts
- packages/docs/PropTables/FlexPropTable.tsx
Fixes [https://github.com/bigcommerce/big-design/issues/661](url)
Flex component has type `wrap-reversed` but the correct value is `wrap-reverse`
Inspected Flex component example and verified correct property is being applied.
> fix(component): change flex-reversed to flex-reverse

- packages/docs/pages/tabs.tsx
- Add a sentence to `When to use`.
- Add `do's  and don'ts` section.
**When to use:**
**Do's and Don'ts  section:**
> feat(docs): add do and don't section in Tabs page

- .github/CODEOWNERS
Adds the @bigcommerce/dev-docs-team as reviewers to any changes in the docs.
To open up visibility to the dev-docs team. This will help gain some visibility into anything we might miss when updating documentation.
> chore(docs): add dev-docs-team as codeowners

- .github/CODEOWNERS
Noticed that when opening a PR in the `packages/docs` repo that the other codeowners didn't get added. This should fix that.
> chore: update documentation codeowners

- packages/docs/pages/progress-circle.tsx
Update progress circle page to use new layout
> feat(docs): update pogress circle page to use new layout

- packages/docs/pages/progress-bar.tsx
Update Progress bar page to use new layout
> feat(docs): update progress bar page to use new layout

- packages/docs/PropTables/RadioPropTable.tsx
- packages/docs/PropTables/shared.tsx
- packages/docs/pages/radio.tsx
Update radio page to use new layout.
> feat(docs): update radio page to use new layout

- packages/docs/PropTables/DropdownPropTable.tsx
- packages/docs/pages/dropdown.tsx
Update dropdown page to use new layout.
> feat(docs): update dropdown page to use new layout

- packages/docs/pages/counter.tsx
- packages/docs/pages/datepicker.tsx
- packages/docs/pages/form.tsx
- packages/docs/pages/inline-message.tsx
- packages/docs/pages/textarea.tsx
Code editor wasn't rendering the corresponding code when switching between tabs inside the implementation section of a documentation page.
**For additional context:** https://github.com/bigcommerce/big-design/pull/746
**Note:** I'm gonna open additional PRs to make it easier to review.
To display the corresponding code when users switch between the tabs.
https://user-images.githubusercontent.com/39739180/156409195-fc4b8fcd-c1b1-4834-8a14-c2f8700c0f14.mp4
> feat(docs): fix code editor bug part 2

- packages/docs/pages/box.tsx
- packages/docs/pages/display.tsx
- packages/docs/pages/flex.tsx
- packages/docs/pages/message.tsx
- packages/docs/pages/tooltip.tsx
Code editor wasn't rendering the corresponding code when switching between tabs inside the implementation section of a documentation page.
**For additional context:** https://github.com/bigcommerce/big-design/pull/746
**Note:** I'm gonna open additional PRs to make it easier to review.
To display the corresponding code when users switch between the tabs.
https://user-images.githubusercontent.com/39739180/156409195-fc4b8fcd-c1b1-4834-8a14-c2f8700c0f14.mp4
> feat(docs): fix code editor bug part 3

- packages/docs/pages/badge.tsx
- packages/docs/pages/breakpoints.tsx
- packages/docs/pages/grid.tsx
- packages/docs/pages/typography.tsx
Code editor wasn't rendering the corresponding code when switching between tabs inside the implementation section of a documentation page.
**For additional context:** https://github.com/bigcommerce/big-design/pull/746
To display the corresponding code when users switch between the tabs.
https://user-images.githubusercontent.com/39739180/156409195-fc4b8fcd-c1b1-4834-8a14-c2f8700c0f14.mp4
> feat(docs): fix code editor bug part 4

- packages/docs/pages/icons.tsx
Update icon page to use new layout.
> feat(docs): update icon page to use new layout

- packages/big-design/src/components/Tabs/Tabs.tsx
- packages/big-design/src/components/Tabs/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tabs/spec.tsx
- packages/docs/PropTables/TabsPropTable.tsx
- packages/docs/pages/tabs.tsx
Add aria roles to the Tabs component
Missing aria roles in a few places:
- Each tab must have an `aria-expanded` role that is set to `true` or `false` if it is active
- Each tab must have an `aria-controls` role that points to the content it displays (this relies on the developer adding the right IDs, so I've updated the example to reflect this)
[Aria rules Source](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tablist_role#description)
**Because we don't have access to the tab panel content, I have assumed IDs of the form `${id}-content`. Open to feedback here, not super reliable, but I don't see another option (short of adding a completely new `TabItem` which opens up its own can of worms)**
> fix(component): add missing aria roles to tabs

- packages/big-design/src/components/Tabs/Tabs.tsx
- packages/big-design/src/components/Tabs/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tabs/spec.tsx
Swap `aria-expanded` to `aria-selected` for Tabs
It looks like it should be `selected`, not `expanded`, based on the w3 guidelines. MDN has inconsistent information on their site (one page says `aria-expanded` and the other says `aria-selected`).
So we're going to side with the w3 on this one. Smells like typo on MDN
> fix(component): use aria-selected for tabs

- packages/big-design-icons/package.json
- yarn.lock
Downgrades `node-fetch` since v3+ is ESM only. We'll need to refactor a bunch of stuff in order to use ESM so downgrading for now.
See "What?"
See "Screenshots/Screen Recordings"
cc. @bc-maksym-konohorov
> chore: downgrade node-fetch to cjs module

- packages/big-design-icons/scripts/build-flags.js
- packages/big-design-icons/scripts/build.js
Changes how we use `tiny-async-pool`. They updated their library to use an iterator approach so we needed to adjust that logic.
See CI.
> fix: tiny-async-pool api changes

- packages/big-design/src/components/Panel/Panel.tsx
- packages/big-design/src/components/Panel/__snapshots__/spec.tsx.snap
Update padding for `Panel` component to 'large'.
To follow the new guideline.
Locally.
> chore(component): update paddings for Panel component

- packages/docs/components/ColorCards/ColorCard.tsx
- packages/docs/components/ColorCards/ColorCards.tsx
- packages/docs/components/ColorCards/availableColors.ts
- packages/docs/components/ColorCards/index.ts
- packages/docs/components/index.tsx
- packages/docs/pages/colors.tsx
Update colors page to use new layout.
Provide better experience to the user when reading or checking the docs.
> feat(docs): update colors page to use new layout

- packages/big-design/src/components/Collapse/spec.tsx
This PR is aimed to refactor Collapse component's tests according to best practices. We take into account recommendations from  Kent C. Dodds [article](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-container-to-query-for-elements). For instance, using `container` for  `query`-ing elements has been removed. Instead,  we replace it with `screen`. 
**NOTE**: userEvent package has been added for switching over fireEvent.
the changes are based on GitHub [issue](https://github.com/bigcommerce/big-design/issues/635) and PRs will be open for each component separately.
The tests have been successfully run locally.
> test(component): refactor collapse component tests

- packages/docs/pages/icons.tsx
- Fix a small typo for the `Icon` tab button
- Add some spacing for the icon names.
Cleanup
See screenshot
> fix(docs): minor page fixes

- packages/docs/components/List/List.tsx
- packages/docs/components/List/styled.tsx
- packages/docs/components/MethodList/MethodList.tsx
- packages/docs/components/SideNav/SideNavGroup/SideNavGroup.tsx
Converts the local documentation `List` over to a Functional Component.
To remove the need for `Pure/ClassComponents`.
Used the `Alert` page, since the side nav + the alert manager functions used the `List` component.
See screenshot.
> chore(docs): convert List to FC

- packages/docs/next.config.js
Changes `assetPath` to `basePath` for links.
Tested locally by providing `/big-design` on dev* mode.
> chore(docs): change assetPath to basePath for links

- packages/big-design-theme/src/helpers/helpers.spec.ts
- packages/big-design-theme/src/helpers/helpers.ts
- packages/big-design-theme/src/helpers/index.ts
Re-exports `hideVisually` from `polished` to consume from the theme helpers.
`hideVisually` is usefully when needing to add Screen Reader only text. This will allow us to consume `polished` version without having to rewrite the styles every time.
N/A 
See CI
> feat(theme): re-export hideVisually from polished

- packages/big-design/src/components/Alert/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Button/Button.tsx
- packages/big-design/src/components/Button/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Button/spec.tsx
- packages/big-design/src/components/Button/styled.tsx
- packages/big-design/src/components/Chip/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/InlineMessage/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Message/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Modal/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/PillTabs/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tabs/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
Add `disabled` attribute to button when `isLoading`
The button is effectively disabled, but not announced as such. Adding
the disabled attribute helps indicate that we can't interact with it.
It also allows us to simplify the logic to fire `onClick`.
<video src="https://user-images.githubusercontent.com/4542735/169184251-c14e8407-acf3-4c57-a353-ba9b389893ca.mov" />
Style has changed slightly according to the disable state, not sure if we want to retain the previous colors. I can look into it if necessary.
Tested in the documentation preview website.
Checked that `onClick` won't fire when `isLoading` or `disabled` are passed.
Unit tests where added as well.
> feat(component): disable button when isLoading

- packages/big-design/src/components/Alert/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Flex/spec.tsx
- packages/big-design/src/components/Flex/types.ts
- packages/big-design/src/components/Flex/withFlex.ts
- packages/big-design/src/components/Grid/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Grid/spec.tsx
- packages/big-design/src/components/Grid/types.ts
- packages/big-design/src/components/Grid/withGrid.ts
- packages/big-design/src/components/InlineMessage/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Message/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Stepper/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tree/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/docs/PropTables/FlexPropTable.tsx
- packages/docs/PropTables/GridPropTable.tsx
- packages/docs/pages/grid.tsx
Expose the [gap](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) prop to Flex / Grid, including row-gap and column-gap. Also, update the corresponding documentation pages to let the users know about this new available props.
Props for Flex component:
- flexGap
- flexRowGap
- flexColumnGap
Props for Grid component:
- gridGap
- gridRowGap
- gridColumnGap
This was a reported enhancement(Fixes #800). These new props are gonna help the user to easily apply spacing between items. 
<table>
<tr>
<td>Grid component
<td>Flex component
<tr>
<tr>
<td><video src= "https://user-images.githubusercontent.com/39739180/171470343-79fa321a-caf9-4fc0-8950-f2476f360a16.mp4"/>
<td><video src= "https://user-images.githubusercontent.com/39739180/171470374-a8c24154-798c-49a4-82dd-87cd60d107ea.mp4" />
<tr> …
> feat(components): Add gap prop into Flex component and Grid component

- packages/big-design/src/components/Worksheet/types.ts
Fix Worksheet onChange typings.
Since the actual accepted items for `onChnage` has the `Array<Item>` interface, but not the `Array<Cell<Item>>`
As we can see from the logs in the console. The changes have the same interface as the `items`.
Locally.
> fix(component): fix Worksheet onChange typings

- packages/big-design/src/components/Table/HeaderCell/HeaderCell.tsx
- packages/big-design/src/components/Table/HeaderCell/styled.tsx
- packages/big-design/src/components/Table/Table.tsx
Keeps the draggable icon constrained instead of stretching potentially fixes: #859
Adding a set width instead of auto keeps the draggable icon column constrained which is useful for when you're creating columns with draggable and selectable elements together. 50px was chosen as it's small enough to still be reasonable on smaller screens while also not constraining the drag icon svg at larger sizes.
https://user-images.githubusercontent.com/99497246/174160129-be342025-91db-45a1-92ab-1893df8c2c0c.mp4
https://user-images.githubusercontent.com/99497246/174160239-3150f090-703e-4601-b0ff-9033bb2caf04.mp4
Test coverage already accommodated the component and this change. Ran the test suite prior to this PR.
> fix(component): add set width if unset

- packages/big-design/src/components/Worksheet/Row/Row.tsx
- packages/big-design/src/components/Worksheet/Worksheet.tsx
- packages/big-design/src/components/Worksheet/hooks/useStore/useStore.ts
- packages/big-design/src/components/Worksheet/spec.tsx
- packages/big-design/src/components/Worksheet/types.ts
- packages/docs/PropTables/WorksheetPropTable.tsx
- packages/docs/pages/worksheet.tsx
Add rows disabling for the Worksheet.
To be able to disable a certain line of the worksheet
Disabling for expanded rows:
Props:
Locally + UT
> feat(component): add rows disabling for the Worksheet

- packages/big-design/src/components/List/Item/Content.tsx
- packages/big-design/src/components/Tooltip/Tooltip.tsx
- packages/big-design/src/components/Tooltip/spec.tsx
- packages/big-design/src/components/Tooltip/styled.tsx
- packages/docs/PropTables/TooltipPropTable.tsx
Removes the `StyledTooltipTrigger` wrapper from the `Tooltip` component. 
This is a breaking change as a result of it:
```
- Removes the `inline` prop on the tooltip
- Strings are not allowed in the `trigger` prop
```
This was causing some layout issues when using it with `Icon` + `Button` components. For example,
```tsx
<Button
iconLeft={
<Tooltip placement="bottom" trigger={<InfoIcon size={20} />}>
Tooltip
</Tooltip>
}
iconRight={<ArrowDropDownIcon />}
>
Label
</Button>
```
Would misalign the icon within the button:
This leaves the layout up to the consumer to position it with a button. I have found `inline-flex` and `inline-grid` good alignment `display` values.
Updated tests to reflect changes.
> feat(component): remove tooltip wrapper

- packages/big-design-icons/package.json
Removes the `.tsbuildinfo` file before releasing the icon package.
The current `prepublishOnly` script removes `dist/` folder, thus removing existing types and because we incrementally build icons then next run of the `build` script won't generate the types again. This causes issues when trying to release big-design as it errors out when running `lerna run build --stream`.
See screenshot.
> chore(icons): remove .tsbuildinfo before releasing

- packages/big-design/src/components/TableNext/DataCell/DataCell.tsx
- packages/big-design/src/components/TableNext/DataCell/styled.tsx
- packages/big-design/src/components/TableNext/Row/Row.tsx
- packages/big-design/src/components/TableNext/Row/useRowState.ts
- packages/big-design/src/components/TableNext/RowContainer/RowContainer.tsx
- packages/big-design/src/components/TableNext/RowContainer/helpers.ts
- packages/big-design/src/components/TableNext/TableNext.tsx
- packages/big-design/src/components/TableNext/hooks/useExpandable/useExpandable.ts
- packages/big-design/src/components/TableNext/spec.tsx
- packages/big-design/src/components/TableNext/types.ts
Add `renderHelperRow` prop. This prop accepts a functional component or class component. This component is gonna help the user render children rows dynamically and showing loader when doing a request. Also, this component must receive a `parentRowIndex` prop which is gonna be helpful to request additional children rows by parent.
Also, another change that was made was inside the expanded props, specifically on the `onExpandedChange` fn. This function is gonna receives two arguments. `expandedItems` and `parentRowIndex`. The last one is gonna help the user fetch data dynamically after clicking on the expanded icon.
Example: 
```tsx
const HelperRow = ({ parentRowIndex }) => {
if (state[parentIndex].isLoading) {
return <LoadingIcon/>
}
if (state[parentIndex] !== undefined && …
```
> TableNext with helperRow component

- packages/big-design/src/components/TableNext/Row/Row.tsx
- packages/big-design/src/components/TableNext/__snapshots__/spec.tsx.snap
Space between the arrow and the next column is too big.
The text in the first column in subrows is not vertically centered.
Fix bug
Before:
After:
Test locally pass
> fix(component): Fix space and alignment in TableNext CHP-7624

- packages/big-design/src/components/index.ts
Removes the `TableNext` export. This ensures a few things:
1. Reduces our main bundle size.
2. Let's consumers know that you need to explicitly import it to use it. It'll be a breaking change when we switch `TableNext` -> `Table`.
3. Allows us to make this an alpha release to test it. **Further releases will not contain this export (see note above).**
To consume, you'll import it via:
```tsx
import { TableNext } from '@bigcommerce/big-design/dist/es/components/TableNext';
```
If you are using TypeScript, add this to your `global.d.ts` or wherever to get types:
```ts
declare module '@bigcommerce/big-design/dist/es/components/TableNext' {
export * from '@bigcommerce/big-design/dist/components/TableNext';
}
```
Consumed in a undisclosed app:
Replaced the node_module locally and consume it in …
> chore: remove TableNext export

- packages/big-design/src/components/Alert/spec.tsx
- packages/big-design/src/components/ButtonGroup/spec.tsx
- packages/big-design/src/components/Checkbox/spec.tsx
We want to replace `fireEvent` with `userEvent` when testing events in components.
Since most of the component's test files use `fireEvent` this PR is just gonna focus on making the change in `Alert`, `ButtonGroup` and `Checkbox` tests files.
Based on react-testing library it’s recommend to use `userEvent` since it resembles how user interacts with our code (in this case for the BD components).
n/a
tests pass.
> chore(deps): use userEvent in alert, button group and checkbox

- packages/big-design/src/components/Worksheet/Cell/Cell.tsx
- packages/big-design/src/components/Worksheet/Row/Row.tsx
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/editors/ModalEditor/ModalEditor.tsx
- packages/big-design/src/components/Worksheet/spec.tsx
- packages/docs/pages/worksheet.tsx
Render empty cells in `Worksheet` when a prop is missing in the item, instead of `undefined`. Shouldn't change the values of onChange until values are actually edited.
When I build it I was under the assumption that the items should always have all the props but this is not always true.
Before:
After:
Updated unit tests to reflect this change.
> fix(component): render empty string when prop is undefined

- packages/big-design/src/components/AccordionPanel/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Panel/Panel.tsx
- packages/big-design/src/components/Panel/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Panel/styled.tsx
Updates the `Panel` components shadow to be `raised` across all breakpoints.
The design team wants to make this a consistent experience across devices.
Updated snapshots.
> feat(component): normalize panel shadow across breakpoints

- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/Switch/spec.tsx
We want to replace `fireEvent` with `userEvent` when testing events in components.
Since most of the component's test files use `fireEvent` this PR is just gonna focus on making the change in `MultiSelect` and `Switch` components
Based on react-testing library it’s recommend to use `userEvent` since it resembles how user interacts with our code (in this case for the BD components)
n/a
Tests pass
> chore(component): use userEvent in multiselect and switch components

- packages/big-design/src/components/Worksheet/Worksheet.tsx
- packages/big-design/src/components/Worksheet/hooks/useWorksheetStore/useWorksheetStore.ts
- packages/big-design/src/components/Worksheet/types.ts
- packages/big-design/src/components/Worksheet/utils.ts
- packages/docs/PropTables/WorksheetPropTable.tsx
- packages/docs/pages/worksheet.tsx
Implement default expanded worksheet rows
To be able to display an expanded row by default.
Locally.
> feat(component): implement default expanded worksheet rows

- packages/big-design/src/components/Worksheet/Cell/styled.tsx
- packages/big-design/src/components/Worksheet/RowStatus/styled.ts
- packages/big-design/src/components/Worksheet/Worksheet.tsx
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/spec.tsx
- packages/big-design/src/components/Worksheet/styled.tsx
- packages/big-design/src/components/Worksheet/types.ts
- packages/docs/PropTables/WorksheetPropTable.tsx
- packages/docs/pages/worksheet.tsx
**Breaking changes (??)**
- Allow custom widths to Worksheet columns.
- Scrollable overflow when columns are wider than table view. 
- Columns wont ellipsis anymore, instead words will wrap.
- When all columns have a fixed width, set Worksheet to auto width (instead of 100%).
**Before**:
**After**:
All columns are fixed width:
At least one column is auto:
Locally, added unit tests.
> feat(component): allow custom column widths and overflow worksheet

- packages/big-design/jest.config.js
- packages/big-design/src/components/TableNext/Actions/Actions.tsx
- packages/big-design/src/components/TableNext/SelectAll/SelectAll.tsx
- packages/big-design/src/components/TableNext/SelectAll/helpers.ts
- packages/big-design/src/components/TableNext/SelectAll/useSelectAllState.ts
- packages/big-design/src/components/TableNext/TableNext.tsx
- packages/big-design/src/components/TableNext/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/TableNext/helpers.ts
- packages/big-design/src/components/TableNext/spec.tsx
Enables `TableNext` to persist selected items across pagination.
For each page, we were returning the indexes of items without accounting for pagination. If you were on page 2, the indexes you were getting back were `{ 0: true, 1: true, 2.0: true, ...etc }`. This made it difficult to both Selected all products across pages and persist selected items across pages. This update aligns with our vision of moving toward using `@tanstack/react-table` or other similar headless table API's to power our `TableNext` component.
https://user-images.githubusercontent.com/10539418/192371874-5c04a746-750c-4a56-8694-293a6e98134f.mov
Here's the `dev.tsx` page I used if you want to test it out yourself:
```tsx
import { TableNext } from '@bigcommerce/big-design/dist/es/components/TableNext';
import React, { …
```
> fix(component): persist selection across TableNext pages

- packages/big-design/src/components/Worksheet/Worksheet.tsx
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/spec.tsx
- packages/big-design/src/components/Worksheet/styled.tsx
- packages/big-design/src/components/Worksheet/types.ts
- packages/docs/PropTables/WorksheetPropTable.tsx
- packages/docs/pages/worksheet.tsx
Sets Worksheet to `table-layout: fixed` and add `minWidth` prop.
Fixes this issue introduced by #975:
The bug is happening because I set `table-layout: auto`, which means the table will try to automatically fit the content in the table (this is cool if we want all columns to remain visible even when shrinking the window), and overflow what doesn't fit (so we get a scroll bar).
Problem is that the `input` element is set to `width: 100%` and unless the `td` has a fixed width (set with the new width prop in the column), it won't calculate the 100% as I expected.
What I'm doing is reverting the table to `table-layout: fixed`. The problem with fixed and having static width columns it that when the table shrinks in size it will shrink all auto columns to 0 to accommodate the fixed width …
> fix(component): prevent column resizing when editing text field

- packages/big-design/src/components/Counter/Counter.tsx
- packages/big-design/src/components/Counter/spec.tsx
- Set type attribute as "button" in Decrease and Increate buttons.
- Remove events in handlers.
- Implement tests.
- Additional update: replace `fireEvent` with `userEvent`.
- To prevent counter input value decrementing when hitting enter to submit a form. Fixes [#940]("https://github.com/bigcommerce/big-design/issues/940").
By default a button has a type "submit" so that is why the input value was changing instead of submitting the form. Also the event.preventDefault() used in the handlers were blocking the event used in a form.
Before:
https://user-images.githubusercontent.com/39739180/193672053-712fcfbb-0ada-418f-a1b4-9c24a6a24351.mp4
After:
https://user-images.githubusercontent.com/39739180/193671323-c2e3abb9-e82d-41cb-9aaa-51a3af6f44c3.mp4
Test pass
> fix(component): fix counter component when submitting a form

- packages/big-design/src/components/TableNext/hooks/useSelectable/helpers.ts
- packages/big-design/src/components/TableNext/spec.tsx
Fixes a bug where selected indexes where getting filtered out that started with the row index you deselected. For example, if you deselected row `2` (index `1`), it would filter out indexes that started with `1` i.e. 13, 1003, etc...
This was causing us to receive an invalid dictionary of selected items when deselecting a table row.
https://user-images.githubusercontent.com/10539418/194344473-54e02f0d-f993-4042-a37f-4e5ac5d871f7.mov
See recording, plus updated tests.
> fix(component): fix table selection bug on individual rows

- packages/big-design/src/components/Worksheet/Worksheet.tsx
Memo context value in Worksheet component. 
Every time we set new Items in `onChange` fn, the Worksheet component re-rendered so a new store was created every time.
```tsx
const WorksheetPage = () => {
const [state, setState] = useState([
{
id: 'variant=1',
label: 'Test name 1',
sku: 'sku 1',
adjustBy: 849,
},
{
id: 'variant=2',
label: 'Test name 2',
sku: 'sku 2',
adjustBy: 345,
},
{
id: 'variant=3',
label: 'Test name 3',
sku: 'sku 3',
adjustBy: 123,
},
]);
return (
<>
<Worksheet
columns={[
{ hash: 'label', header: 'Product name' },
{ hash: 'sku', header: 'SKU' },
{ hash: 'adjustBy', header: 'Adjust by', type: 'number' },
]}
items={state}
key={0}
onChange={(changedItems) => {
const res = state.map((item) => {
const changedItem = changedItems.find((changedItem) => changedItem.id === …
```
> fix(component):  worksheet context

- packages/big-design/src/components/Worksheet/Cell/Cell.tsx
- packages/big-design/src/components/Worksheet/Modal/Modal.tsx
- packages/big-design/src/components/Worksheet/editors/ModalEditor/ModalEditor.tsx
- packages/big-design/src/components/Worksheet/editors/SelectEditor/SelectEditor.tsx
- packages/big-design/src/components/Worksheet/editors/TextEditor/TextEditor.tsx
- packages/big-design/src/components/Worksheet/editors/ToggleEditor/ToggleEditor.tsx
- packages/big-design/src/components/Worksheet/hooks/useEditableCell/useEditableCell.ts
- packages/big-design/src/components/Worksheet/hooks/useKeyEvents/useKeyEvents.ts
- packages/big-design/src/components/Worksheet/hooks/useWorksheetStore/useWorksheetStore.ts
- packages/big-design/src/components/Worksheet/spec.tsx
Keys presses fill the field in with the key code in worksheet. 
We are passing the key code as an argument in `editSelectedCell` fn when entering info in a cell.
Examples: 
- if we use the `command` key the cell is filled with its corresponding code: 'Meta'
- if we press key `a` the code its `a`
Current solution (patch):
- Checking the length of the key. And check when using Meta and Control to be able to copy content in a cell.
Note: would be good to refactor our current code but might take more time.
Before:
https://user-images.githubusercontent.com/39739180/195959199-bdb4b31d-0d87-4b8d-bb89-85feb8032436.mp4
After
https://user-images.githubusercontent.com/39739180/196284677-91f906ac-3f09-4b4e-8c10-2c67dc210a49.mp4
Test pass
> fix(component): keys presses fill the field in with the key code in worksheet

- packages/big-design/src/components/Pagination/Pagination.tsx
- packages/big-design/src/components/Pagination/spec.tsx
- packages/big-design/src/components/Table/TablePagination/TablePagination.tsx
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/TableNext/TablePagination/TablePagination.tsx
- packages/big-design/src/components/TableNext/spec.tsx
- packages/docs/PropTables/PaginationPropTable.tsx
Adding a `label`, `previousLabel` , `nextLabel` and `getLabel` prop to the Pagination component that customise the labels of the navigation buttons and range selector 
Allow greater customisability of the component.
https://user-images.githubusercontent.com/109577044/195255292-47d6a00d-ea04-4765-858e-30ceebe9dcf5.mov
Added jest spec tests to define behaviour of new pagination props.
> feat(component): provide props for customising pagination button labels

- packages/big-design/src/components/AccordionPanel/Accordion/Accordion.tsx
Fixes an issue that when accordion headers are clicked, they fire the 'enter' event, causing forms to submit. See issue https://github.com/bigcommerce/big-design/issues/1022
Tested by adding type='button' to the StyledAccordionButton props and then clicking the attribute header.
> fix(component): add type button to StyledAccordionButton (1022)

- packages/big-design-icons/README.md
Previous url redirects to new docs and to an empty page. I believe we need to point to the icons library in google fonts. 
[Old url](https://material.io/resources/icons/?style=round)
[New url](https://fonts.google.com/icons?selected=Material+Icons&icon.style=Rounded)
> chore: update material icons url

- packages/big-design/src/components/AccordionPanel/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Panel/Panel.tsx
- packages/big-design/src/components/Panel/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Panel/spec.tsx
- packages/big-design/src/components/Panel/styled.tsx
Adds the border radius back to the `Panel` component on tablet+ screens.
This was a regression from https://github.com/bigcommerce/big-design/pull/962. The panel shouldn't have a border radius only on mobile devices.
Fixes #1031
Updated tests and snapshots.
> fix(component): add border-radius back to Panel component

- packages/big-design/src/components/TableNext/Actions/Actions.tsx
- packages/big-design/src/components/TableNext/Row/Row.tsx
- packages/big-design/src/components/TableNext/Row/spec.tsx
- packages/big-design/src/components/TableNext/Row/useRowState.ts
- packages/big-design/src/components/TableNext/RowContainer/RowContainer.tsx
- packages/big-design/src/components/TableNext/RowContainer/spec.ts
- packages/big-design/src/components/TableNext/SelectAll/SelectAll.tsx
- packages/big-design/src/components/TableNext/SelectAll/helpers.ts
- packages/big-design/src/components/TableNext/hooks/useSelectable/helpers.ts
- packages/big-design/src/components/TableNext/hooks/useSelectable/useSelectable.ts
- packages/big-design/src/components/TableNext/spec.tsx
Removes child row selection from TableNext
We want to come up with a better pattern for child selection, and child selection was causing some issues in current implementations using this new component. 
Parent row selection still functions and child rows are read only
> Remove child selection from TableNext

- packages/big-design/src/components/Form/Form.tsx
- packages/big-design/src/components/Form/Group/Group.tsx
- packages/big-design/src/components/Form/Group/styled.tsx
- packages/big-design/src/components/Form/useFormContext.ts
Allows fullWidth inline form fields. Fixes #660
To add consistency with the rest of form fields that have full width enabled.
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="945" alt="Screen Shot 2022-11-02 at 21 09 20" src="https://user-images.githubusercontent.com/10539418/199635634-4520c14b-83e3-4f6a-a56c-5f0f2fcc82a6.png"/>
<td><img width="945" alt="Screen Shot 2022-11-02 at 21 08 49" src="https://user-images.githubusercontent.com/10539418/199635646-3636de20-d2ec-4685-8f86-108a9387a92b.png" />
</table>
Manually tested in the browser.
> feat(component): allow fullWidth on inline form fields

- packages/big-design/src/components/Pagination/Pagination.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/TableNext/__snapshots__/spec.tsx.snap
Add button type for the buttons used in pagination
For most browsers the default type of button is submit. When this component is used in a `form`, it will submit the form when any button is clicked
After (when clicking on the buttons in pagination, the form no longer submitted):
Before (when clicking on the buttons in pagination, the form is submitted):
Explained above
> fix(component): specify button type for pagination

- packages/big-design/src/components/TableNext/Row/Row.tsx
Fix horizontal alignment for columns by adding missing props to the flex component.
**Note:** both examples have `align === right` for the `stock` column.
**Before fix:**
**After fix:**
Locally.
> fix(component): fix table-next column alignment

- packages/big-design/package.json
- packages/big-design/src/components/Box/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Box/spec.tsx
- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/spec.tsx
- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Pagination/spec.tsx
- packages/big-design/src/components/PillTabs/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/TableNext/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Timepicker/spec.tsx
- packages/configs/jest/jest.config.js
- yarn.lock
Updates `downshift` to the latest major version. This also tackles some a11y improvements for the `Dropdown`, `Select`, and `MultiSelect` components.
We want to stay current with the latest ARIA 1.2 spec which this new version of `downshift` adheres to.
N/a?
- Updated Snapshots
- Added new tests to showcase the `aria-labelledby` issue.
- Refactored existing tests to handle a11y updates.
> feat(deps): update downshift and apply a11y patterns

- packages/big-design/src/components/StatefulTree/spec.tsx
- packages/big-design/src/components/Tree/Tree.tsx
- packages/big-design/src/components/Tree/TreeNode/TreeNode.tsx
- packages/big-design/src/components/Tree/spec.tsx
- packages/big-design/src/components/Tree/types.ts
Focuses on the `TreeItem` whenever the `document.activeElement` is within the `Tree`.
Also, updates `Tree` tests to reflect better testing patterns (see #635).
This fixes the behavior we've seen for a while which causes the tree to be initially focused on initial render. This causes some accessibility concerns as the we place the user onto the tree instead of the initial page or, in the case of modals, launch order.
<table>
<tr>
<td>Before
<td>After
<tr>
<td><video src="https://user-images.githubusercontent.com/10539418/210616392-446f8357-eecf-4f4d-a426-c61ea79b02a9.mov" />
<td><video src="https://user-images.githubusercontent.com/10539418/210616149-bf553eac-49c6-487a-9016-b0cf461af9df.mov" />
</table>
Added two additional tests, along with updating the `Tree` tests to reflect better …
> fix(component): only focus on TreeItem when focus within Tree component

- packages/big-design/src/components/Table/HeaderCell/HeaderCell.tsx
- packages/big-design/src/components/Worksheet/Worksheet.tsx
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/spec.tsx
- packages/big-design/src/components/Worksheet/types.ts
- packages/docs/PropTables/WorksheetPropTable.tsx
- packages/docs/pages/worksheet.tsx
Added header tooltip for worksheet component.
Refactored rendering of the tooltip for the Table component.
(packages/big-design/src/components/Table/HeaderCell/HeaderCell.tsx)
To be able to leave a short description of the column.
Locally + UT.
> feat(component): add header tooltip for worksheet component

- packages/big-design/src/components/TableNext/Actions/Actions.tsx
- packages/big-design/src/components/TableNext/Row/Row.tsx
- packages/big-design/src/components/TableNext/Row/spec.tsx
- packages/big-design/src/components/TableNext/Row/useRowState.ts
- packages/big-design/src/components/TableNext/RowContainer/RowContainer.tsx
- packages/big-design/src/components/TableNext/SelectAll/SelectAll.tsx
- packages/big-design/src/components/TableNext/SelectAll/helpers.ts
- packages/big-design/src/components/TableNext/SelectAll/useSelectAllState.ts
- packages/big-design/src/components/TableNext/TableNext.tsx
- packages/big-design/src/components/TableNext/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/TableNext/hooks/useExpandable/useExpandable.ts
- packages/big-design/src/components/TableNext/hooks/useSelectable/helpers.ts
- packages/big-design/src/components/TableNext/hooks/useSelectable/useSelectable.ts
- packages/big-design/src/components/TableNext/spec.tsx
- packages/big-design/src/components/TableNext/types.ts
1. Enable child row selection  (isChildrenRowsSelectable)
2. Get rows by and identifier (getRowId)
3. Add and update props. (initialSelectedParentRows, expandedRowSelector)
Note: Please review by commit.
1. Let the user decide to make all the children selectable in a table or not.
2. Let the user decide how to retrieve the selected rows and expanded rows by an identifier (the  default is gonna by indexes)
3. Based on the new changes of how to retrieve selected rows, it was necessary to add initialSelectedParentRows prop to identify the initial selected parent rows across pages, since when using pagination not all the items are passed to the component, it is just passes the current items by page. 
Also, update expandedRowSelector prop name to getChildren since it better describes the …
> Enable child row selection in TableNext

- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/styled.tsx
Fix the alignment of the worksheet header (checkbox column).
To be consistent with the guidelines.
BEFORE
NOW
Locally.
> fix(component): fix alignment of the worksheet header

- packages/big-design/src/components/Worksheet/Cell/Cell.tsx
- packages/big-design/src/components/Worksheet/Cell/styled.tsx
- packages/big-design/src/components/Worksheet/Row/Row.tsx
- packages/big-design/src/components/Worksheet/Row/styled.ts
- packages/big-design/src/components/Worksheet/Worksheet.tsx
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/editors/ToggleEditor/ToggleEditor.tsx
- packages/big-design/src/components/Worksheet/editors/ToggleEditor/styled.ts
- packages/big-design/src/components/Worksheet/styled.tsx
1. Add sub-rows indicators for the worksheet.
2. Changes in the worksheet according to the new guidelines.
The guidelines is updated.
Locally.
> feat(component): add sub-rows indicators for worksheet

- packages/big-design/src/components/AccordionPanel/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Panel/Panel.tsx
- packages/big-design/src/components/Panel/spec.tsx
- packages/docs/PropTables/PanelPropTable.tsx
- packages/docs/pages/panel.tsx
Add description to Panel component. Resolves #1109.
I opted to allow the description a `string` or as a `ReactNode`. This will allow the flexibility to include links in the description. Let me know if we want to showcase the "custom" ReactNode functionality.
Should we include more do's and don'ts for this prop? @bigcommerce/product-design 
Without description (remains the same):
Unit tests
> feat(component): add description to Panel

- yarn.lock
Run `yarn upgrade-interactive` to bump deps instead of using dependabot.
Again, tired of manually merging dependabot PRs.
N/A
See CI.
> chore(deps): bump additional deps

- packages/big-design/package.json
- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/Select/Select.tsx
- packages/big-design/src/components/Select/spec.tsx
- yarn.lock
Bump of `downshift` to `7.x` enabled by default the opening of the menu when the input was focused. This reverts that behavior.
Unit test + local.
> fix(component): prevent focus from opening menu in selects

- packages/big-design/src/components/Worksheet/Cell/Cell.tsx
- packages/big-design/src/components/Worksheet/Worksheet.tsx
- packages/big-design/src/components/Worksheet/hooks/useKeyEvents/useKeyEvents.ts
- packages/big-design/src/components/Worksheet/hooks/useWorksheetStore/useWorksheetStore.ts
- packages/big-design/src/components/Worksheet/spec.tsx
1. Implement the selection of multiple cells in a row using Shift+arrow buttons.
2. Implement the selection of multiple cells in a row within a column by holding SHIFT and clicking on the first and the last cells in the selection.
https://user-images.githubusercontent.com/84462142/226999149-65a2b457-abb1-4577-86af-8a2b7bf4e1e8.mov
Locally + UT
> feat(component): add cell selection with a keyboard

- packages/big-design/src/components/ButtonGroup/ButtonGroup.tsx
- packages/big-design/src/components/ButtonGroup/spec.tsx
Adds `type=button` to the ButtonGroup dropdown trigger.
When we render a `ButtonGroup` inside of a form and the user clicks on the dropdown trigger it submits the form as we can't pass a type button to the trigger.
n/a
Unit
> chore(component): make ButtonGroup trigger a type button

- packages/big-design/src/components/Dropdown/Dropdown.tsx
- packages/big-design/src/components/Dropdown/spec.tsx
We (as in @deini) noticed that the `Dropdown` was triggering `onItemClick` whenever we blurred away from the dropdown menu. Downshift [adds a `selectedItem`](https://github.com/downshift-js/downshift/blob/master/src/hooks/useSelect/reducer.js#L150-L158) whenever the highlighted index is `>=0` (which ours is `0` by default). This causes the `onSelectedItemChange` function to trigger causing `onItemClick` to run when the dropdown is blurred.
Replicated issue:
https://user-images.githubusercontent.com/10539418/230143812-e4cf58ff-a6bf-4277-955e-0c30d225f1e1.mp4
Added new tests to the component and ensured coverage was met.
> fix(component): prevent selectedItem from being set on Dropdown blur

- packages/big-design-theme/jest.config.js
- packages/big-design-theme/package.json
- packages/big-design-theme/setupTests.ts
- packages/big-design-theme/tsconfig.json
- packages/big-design/package.json
- packages/big-design/setupTests.ts
- packages/big-design/src/components/Counter/spec.tsx
- packages/big-design/src/components/Pagination/spec.tsx
- packages/big-design/src/components/Select/spec.tsx
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/TableNext/spec.tsx
- packages/big-design/src/utils/warning/spec.ts
- yarn.lock
Cleans up the all the error and warnings logs from our test suites. Also added `jest-fail-on-console` to prevent this from happening in the future.
To make it 💅 
Pretty test suite 😮 
`jest-fail-on-error` test:
> chore: cleanup test logs and add jest-fail-on-console

- packages/big-design/src/components/Worksheet/Cell/Cell.tsx
- packages/big-design/src/components/Worksheet/Cell/styled.tsx
- packages/big-design/src/components/Worksheet/Row/Row.tsx
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/spec.tsx
- packages/big-design/src/components/Worksheet/types.ts
- packages/docs/PropTables/WorksheetPropTable.tsx
- packages/docs/pages/worksheet.tsx
Add notation for worksheet cells
- It should be applicable to a cell of any type.
- The indicator color should be customizable within the BigDesign color palette.
- The message should be customizable.
- The indicator position is always the same – the top right corner.
- The tooltip position by default should be on the right of the indicator and automatically adjusted if it doesn’t fit the screen.
To be able to provide a way to show additional notes/comments/instructions on a particular cell level.
https://user-images.githubusercontent.com/84462142/231280748-fc82a7ce-c25c-4d72-8b73-2cb0a3cfb537.mov
Locally + UT
> feat(component): add notation for worksheet cells

- packages/big-design/src/components/Worksheet/Cell/Cell.tsx
- packages/big-design/src/components/Worksheet/Row/Row.tsx
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/hooks/useWorksheetStore/useWorksheetStore.ts
- packages/big-design/src/components/Worksheet/utils.ts
- Add conditional rendering for the `Rows` instead of `display: none` to improve initial rendering performance;
- Improve `Cell` performance by adding `Maps` for the `selectedCells, invalidCells and editedCells` entities to remove cycles in the `zustand` selectors.
When the `Worksheet` component contains `50 rows` + every row has `40 children` browsers completely crush.
**Before:**
Browser stuck.
**Now:**
https://github.com/bigcommerce/big-design/assets/9980803/8f9e2019-2e8f-4d1b-88da-20c3a3569319
Existing tests + locally.
> chore(component): improving worksheet performance

- packages/big-design-theme/package.json
- packages/big-design-theme/tsconfig.declarations.json
As part of #1187 we added `setupTests.ts` to the `include` in `tsconfig.json`. This caused the generated types to not be flat. You can see below in the screenshots that adding the `setupTests.ts` caused the types to be located in a `src/` folder instead.
We noticed this issue on the latest published version. This should fix the type declarations being exported on the correct path.
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/bigcommerce/big-design/assets/10539418/a9502f99-073c-4601-bda3-8916484e801c" />
<td><img src="https://github.com/bigcommerce/big-design/assets/10539418/5e65f700-affa-473d-8b28-96d2dc33b008)" />
</table>
> fix: declaration tsconfig for theme publishing

- packages/big-design/src/components/Datepicker/styled.ts
Fix the broken template on the date-picker.
Locally.
> fix(component): fix date-picker extra label

- packages/big-design/src/components/Badge/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Badge/styled.tsx
- packages/big-design/src/components/Panel/Panel.tsx
- packages/big-design/src/components/Panel/spec.tsx
- packages/docs/PropTables/PanelPropTable.tsx
- packages/docs/pages/panel.tsx
Added Badge props to Panel component
To be able to show a badge for the Panel component
Manual testing
> feat(component): added Badge props to Panel component

- packages/big-design/package.json
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/PillTabs/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/TableNext/__snapshots__/spec.tsx.snap
- yarn.lock
Upgrade `downshift` to `7.6.0`
Snyk says we should but doesn't seem to update lockfiles: https://github.com/bigcommerce/big-design/pull/1247
CircleCI.
> chore(deps): bump downshift

- packages/big-design/src/components/Toggle/Toggle.tsx
- packages/big-design/src/components/Toggle/index.ts
- packages/big-design/src/components/Toggle/spec.tsx
- packages/big-design/src/components/Toggle/styled.ts
- packages/big-design/src/components/index.ts
- packages/docs/PropTables/TogglePropsTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/pages/toggle.tsx
Create a `Toggle` component.
FOCUSED:
DISABLED:
HOVERED:
Locally + UT.
> feat(component): create Toggle component

- packages/big-design/src/components/Form/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Input/styled.tsx
Change text color in disabled input to `Secondary60` / `#5E637A`
According to figma color should be `Secondary60`
https://www.figma.com/file/duwtpbP2tnLLQQmAkwtrNC/BigDesign-Lib?type=design&node-id=573-1945&mode=design&t=yDNokNBDsjl1Yukc-4
Manually tested on latest google chrome.
> fix(component): update disabled input text color

- .eslintrc.js
- package.json
- packages/docs/design-docs/ux-writing/glossary.mdx
- packages/docs/design-docs/ux-writing/grammar.mdx
- packages/docs/design-docs/ux-writing/index.mdx
- packages/docs/design-docs/ux-writing/interactions.mdx
- packages/docs/design-docs/ux-writing/localization.mdx
- packages/docs/design-docs/ux-writing/mechanics.mdx
- packages/docs/design-docs/ux-writing/status-messages.mdx
- packages/docs/design-docs/ux-writing/the-basics.mdx
- packages/docs/design-docs/ux-writing/writing-for-mobile.mdx
- yarn.lock
> [!NOTE]
> If using VSCode, make sure you add `mdx` into your VSCode `eslint.validate` settings.
These are the MDX files needed to showcase our Ux Writing Guide on the dev docs portal.
Dev docs portal pulls information when building from diverse sources. The recommendation from the team is to keep all BigDesign information within the BigDesign repo.
UX Writing guide will be the first item to make it into public from the renewed BigDesign documentation.
You can check all screenshots at the Figma asset created to provide feedback.
https://www.figma.com/file/XWxcx6FLg1tGevfxkqFLcA/UX-writing-guide---redlining?type=whiteboard&node-id=0%3A1&t=EnmZXmRSz39KzwpT-1
No tests associated to these docs as this will be parsed by the dev docs repo.
> docs: add ux writing guide mdx to support dev docs portal

- CONTRIBUTING.md
- README.md
- lerna.json
- packages/big-design-theme/README.md
Changes the publish branch from `master` to `main`.
Slight miss from changing the default branch name 2 weeks ago.
> chore: change publish branch to main

- packages/big-design/src/components/Input/Input.tsx
Fix unselecting via chips list for multi-select.
The issue appears because of `key` collision, since the `key` for a `Chip` consisted only from `label` which is non unic.
BEFORE
https://github.com/bigcommerce/big-design/assets/84462142/765e5693-41a2-4e5f-ba6c-385f8233ca0a
AFTER
https://github.com/bigcommerce/big-design/assets/84462142/f3631e0d-f0ad-41dc-b558-609f28f4e14f
Locally.
> fix(component): fix unselecting via chips list for multi-select

- packages/big-design/src/components/FileUploader/DropZone.tsx
- packages/big-design/src/components/FileUploader/FileUploader.tsx
- packages/big-design/src/components/FileUploader/styled.ts
- packages/docs/PropTables/FileUploaderPropTable.tsx
Add icon props for FileUploader drop-zone.
To be able to set custom icon.
Locally.
> feat(component): add icon prop for FileUploader drop-zone

- .github/dependabot.yml
- package.json
- packages/big-design-icons/package.json
- packages/big-design-icons/scripts/downloader.js
- yarn.lock
- Removes the usage of `node-fetch` in favor of the native `fetch` API available to us in v16+
- "Pins" the `@commitlint/*` packages to the latest version without ESM only support.
Removes a dep + we would need to rework the repo to support ESM only.
N/A
Downloader script still works + I was able to commit for this PR:
> chore: bump @commitlint/* and cleanup dep

- packages/big-design/src/components/Alert/Alert.tsx
- packages/big-design/src/components/Alert/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Alert/spec.tsx
Adds an `aria-labelledby` to the `Alert` component, which is associated to the optional `header`.
1. To provide screen readers with an accessible 'name' for the alert
2. Also useful in tests, proving that the correct alert was selected
New test: https://github.com/bigcommerce/big-design/pull/1388/files#diff-c8881538168695ea6e7ca5ba1d22e808a91da2fe5552072b18ede0869ebee815R91-R96
> feat(component): allow Alerts to be labelled by their header

- package.json
- packages/big-design-icons/package.json
- packages/big-design-theme/package.json
- packages/big-design/package.json
- packages/configs/package.json
- packages/docs/package.json
- packages/examples/package.json
- pnpm-lock.yaml
Updates typescript to the latest version to fix the build outputs.
Typescript Issue: https://github.com/microsoft/TypeScript/issues/57956
Types we using absolute paths, which was causing the types to be `any`.
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/bigcommerce/big-design/assets/10539418/2f3dfbd9-7cf3-4672-82cd-835c7cf2b0c2" />
<td><img src="https://github.com/bigcommerce/big-design/assets/10539418/7e3ae46f-0302-48d8-8fe4-ee6cd9fd4401" />
</table>
> fix: typescript build output with wrong imports

- .circleci/config.yml
Installs any corepack installed package managers in a folder with permissions.
Running into a `Internal Error: EACCES: permission denied, unlink '/usr/local/bin/pnpm'` when activating pnpm.
https://app.circleci.com/pipelines/github/bigcommerce/big-design/6077/workflows/469edca2-53d5-41ec-a6d0-75e629711561/jobs/28248
N/A
See CI.
> chore(ci): install package managers in ~/bin folder

- packages/docs/components/NextLink/NextLink.tsx
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/components/SideNav/SideNavLink/SideNavLink.tsx
- packages/docs/components/SideNav/SideNavLogo/SideNavLogo.tsx
- packages/docs/components/SideNav/SideNavLogo/styled.tsx
- packages/docs/components/SideNav/styled.tsx
- packages/docs/next.config.js
- packages/docs/package.json
- packages/docs/pages/_app.tsx
- pnpm-lock.yaml
Updates the side nav on the docs side to use a radix-ui scroll area. Alongside that, I had to adjust a few layout bits in order to accommodate this new component. This helped clean up a few bits of legacy code that we should've removed a while ago. 
Some of the layout changes:
- Added more width to the content and side nav
- Removed helpful links and hoisted the Github link up since I know it's used a lot.
The scroll bar was continuously present which was a bit annoying. Using radix allows it to auto-hide and customize the scroll bar with cross-browser support. Increasing the width of the content and side-nav also helps make the docs look nicer.
https://github.com/bigcommerce/big-design/assets/10539418/d9152fe1-9cab-4f64-8875-979ef581a6b9
> refactor(docs): update side-nav to use radix scrollbar

- packages/big-design-icons/package.json
- packages/big-design-theme/package.json
- packages/big-design/package.json
- packages/configs/ts/tsconfig.json
- packages/docs/package.json
- pnpm-lock.yaml
Switches over to the official `@styled/typescript-styled-plugin`.
The old one was deprecated and no longer maintained.
N/A
See CI
> chore(deps): switch over to forked typescript-styled-plugin

- packages/docs/.babelrc
- packages/docs/next.config.js
- packages/docs/package.json
- pnpm-lock.yaml
Removes the custom babel setup for the docs site.
SWC has full support now for styled-components: https://github.com/vercel/next.js/issues/30802
N/A
CI + ran it locally and didn't get any console issues.
> chore(deps): remove babel setup for docs

- packages/big-design/src/components/AccordionPanel/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Panel/Panel.tsx
- packages/big-design/src/components/Panel/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Panel/spec.tsx
Currently a contentless (or `children`-less) `Panel` component renders with excessive margin under its header.
This PR removes that extra margin.
I am not sure if a contentless use of `Panel` was originally envisioned, but the prop is optional and design are looking to use it for 'placeholders'. For example, the `Shipping` panel on Manual Orders remains empty until preceding mandatory sections are filled.
Note: only the final variant is affected by this change
- Screenshots from documentation app above
- Passing existing tests, proving no other scenarios were affected
- New snapshot test to defend the new conditional styling
> fix(component): remove excess margin from contentless Panel

- packages/big-design/src/components/Collapse/Collapse.tsx
We need to add a "type" tag to the Collapse button because otherwise it will behave by default like "type:submit" which may cause the form to submit unexpectedly.
Before:
https://github.com/bigcommerce/big-design/assets/130665807/e6fd460a-6557-4491-8d2f-86b68d6e88c5
After:
https://github.com/bigcommerce/big-design/assets/130665807/294b5d9e-4770-425d-9d25-2b046dbb9780
Manual tests
> feat(component): type added to the Collapse button

- packages/big-design/src/components/List/Item/styled.tsx
- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/List/styled.tsx
- packages/big-design/src/components/Pagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/PillTabs/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/TableNext/__snapshots__/spec.tsx.snap
This is an attempted fix for #1441 but alternative suggestions welcome. 
This removes [the fix](https://github.com/bigcommerce/big-design/pull/1322) for body scroll in long multi-selects because it conflicts with the [hideVisually](https://polished.js.org/docs/#hidevisually) helper that's being used to hide the native browser input. 
See #1441
Before:
https://share.descript.com/view/uD0QKyXLOUM
After:
https://share.descript.com/view/pp4SbBeHmtN
Regression test on Select https://share.descript.com/view/R56Sgg2B4yR
> fix(component): fix extra body scroll due to multi-select without visual regression

- packages/docs/pages/display.tsx
Fixes a small typo on the docs in the display page:
To use proper grammar
N/A
N/A
> fix(docs): typo on display docs page

- packages/big-design/src/components/List/Item/Item.tsx
- packages/big-design/src/components/List/List.tsx
- packages/big-design/src/components/MultiSelect/MultiSelect.tsx
- packages/big-design/src/components/MultiSelect/spec.tsx
- packages/big-design/src/components/MultiSelect/types.ts
- packages/docs/PropTables/MultiSelectPropTable.tsx
Implement `select all` for multi-select component;
To be able to select/unselect all options by one click.
https://github.com/bigcommerce/big-design/assets/84462142/a8df07b7-0bd7-447a-a369-0c9aa48fcb99
Locally + UT.
> feat(component):  implement `select all` for multi-select component

- packages/big-design/src/components/Worksheet/hooks/useEditableCell/useEditableCell.ts
Avoid displaying `NaN` in number cell (Worksheet).
`NaN` is technical value, and is not clear for final user.
Locally.
> fix(component): avoid displaying NaN in number cell

- packages/big-design/src/components/Worksheet/Row/Row.tsx
Fix formatting of the worksheet cell with the default type
When there is no explicitly defined type of the worksheet column, the column has type 'text', and formatting should work for such columns type, but it does not work.
https://github.com/bigcommerce/big-design/assets/84462142/9d6968cb-f25e-4dd1-a6ba-d39909700864
Locally.
> fix(component): fix formatting of the worksheet cell with the default type

- .circleci/config.yml
- package.json
- pnpm-lock.yaml
Adds a `packageManager` field and updates pnpm to `9.5.0`. That comes with using the new lockfile version 9 which helps with merge conflicts.
N/A
See CI.
> chore: add packageManager version

- .circleci/config.yml
- package.json
- pnpm-lock.yaml
Downgrades pnpm to v8.
Started getting the following issue when trying to publish. Not entirely sure how to fix it yet and want to unblock a release.
```bash
77 error Error: Command failed with exit code 1: corepack pnpm install --lockfile-only --ignore-scripts
77 error Scope: all 8 workspace projects
77 error  WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
77 error Progress: resolved 1, reused 0, downloaded 0, added 0
77 error /Users/chancellor.clark/repositories/big-design/packages/docs:
77 error  ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@bigcommerce%2Fexamples: Not Found - 404
77 error
77 error This error happened while installing a direct dependency of /Users/chancellor.clark/repositories/big-design/packages/docs
77 error
77 error …
```
> chore(deps): downgrade pnpm to v8

- packages/big-design/package.json
- pnpm-lock.yaml
Removes `@testing-library/react-hooks` library.
It is currently being unused and is actually "deprecated" in favor of importing it from the `@testing-library/react` package instead. See https://github.com/testing-library/react-hooks-testing-library?tab=readme-ov-file#a-note-about-react-18-support
N/A
N/A
> chore(deps): remove @testing-library/react-hooks

- packages/big-design/src/components/Datepicker/Datepicker.tsx
- packages/big-design/src/components/Datepicker/spec.tsx
- Ensure that `onBlur` and `onFocus` callbacks are honoured and ran by the `Datepicker`
- Both `onBlur` and `onFocus` appear as current valid `Datepicker` props
- Useful to have them for form libraries and custom validation logic
(Misalignment of next/previous month caused by zooming in for the video)
https://github.com/user-attachments/assets/09a86450-b320-40a4-8bff-c0c46c6a183b
- New test proving behaviour: https://github.com/bigcommerce/big-design/pull/1478/files#diff-406d20a98aca0b8a48dc23571b83cb154592e97c22365d041b8ab32e8e016f7bR134-R157
> fix(component): fix onBlur and onFocus support for Datepicker

- .circleci/config.yml
- .gitignore
- package.json
- pnpm-lock.yaml
- turbo.json
Switches the repo over to using `turbo` instead of `lerna`'s built-in `nx` caching functionality. Also updates CI to use the caching benefit using remote caching.
This is part of the path to removing lerna from the repo.
N/A
Latest test run in CI is using Turbo Remote Caching.
> chore: use turborepo instead of lerna + nx

- .changeset/config.json
- .github/workflows/changesets.yml
- package.json
- pnpm-lock.yaml
Adds the `changesets` GitHub action to the repo.
_Note: This has to be a GitHub action as changesets doesn't have a orb for CircleCI._
This is part of an effort to make versioning and publishing new versions of the repo easier.
N/A
This is a similar setup to [@bigcommerce/catalyst](https://github.com/bigcommerce/catalyst/blob/main/.github/workflows/changesets-release.yml). Unfortunately, this can only be tested fully once merged to `main`.
> chore: add changesets

- .github/workflows/changesets.yml
Flips around the script order to account for the repo needing to be built before linted.
N/A
> fix(ci): fix script order for changesets

- .changeset/lazy-glasses-relax.md
- packages/big-design-theme/src/system/breakpoints.ts
- packages/docs/pages/breakpoints.tsx
Adding a wide breakpoint for large screen definitions
We have gathered through analytics that the majority of users use wide monitors, being 1920x1080 the most common screen resolution. Our form pages look too narrow on this case. We are to use this definition in patterns moving forward.
> feat: add wide breakpoint for large screens

- .circleci/config.yml
- .husky/commit-msg
- .husky/pre-commit
- CONTRIBUTING.md
- package.json
- pnpm-lock.yaml
This aims to move local validation to CI.
- `lint-staged` was running `eslint --fix` which you can run `pnpm lint --fix` instead.
- commit messages were only being validated locally and should be validated by CI.
N/A
Bad run: https://app.circleci.com/pipelines/github/bigcommerce/big-design/6536/workflows/c739ed0c-5845-4063-bead-2769a1963d14/jobs/31203
Good run: https://app.circleci.com/pipelines/github/bigcommerce/big-design/6535/workflows/a1729061-7ecd-4491-b64e-62b4ec7e4a0b/jobs/31195
> chore: ensure scripts run in CI

- .changeset/polite-swans-happen.md
- packages/docs/next.config.js
- packages/docs/package.json
- pnpm-lock.yaml
Uses the version from `package.json` to inject the examples version for the codesandbox link.
When changesets bumps the versions of packages, it'll also update the package.json in the docs repo. `changesets` doesn't update the `pnpm-lock.yaml` which causes a mismatch when trying to install with `--frozen-lockfile`.
N/A
> refactor(docs): use local file to get examples version

- .changeset/nervous-ants-nail.md
- packages/docs/next.config.js
- packages/docs/package.json
- pnpm-lock.yaml
Uses the native module transpilation instead of the `next-transpile-modules` package.
This functionality has been built in since `next@13`. That means the package is EOL:
https://github.com/martpie/next-transpile-modules/releases/tag/the-end
N/A
> refactor(docs): replace next-transpile-modules package

- .github/workflows/changesets.yml
Elevates the `permissions` field to the root workflow to extend the default permissions rather than reset them (by being in a job).
> chore(ci): apply correct permissions for release action

- .github/dependabot.yml
- .github/workflows/changesets.yml
- commitlint.config.js
- package.json
- pnpm-lock.yaml
Tailors commitlint to handle dependabot PR's and loosens some of the rules brought in by `@commitlint/config-conventional`. Dependabot PR's are not able to be tailored to our specific commitlint rules, so we are needing to relax them a bit. I also bumped the versions of commitlint as we are not relying on them as scripts, but instead relying on them to be ran in a node environment with the binary. The next major version was ESM only, which doesn't matter when using a built binary.
> chore: adjust commitlint config to account for dependabot

- .github/workflows/changesets.yml
After doing a bit more digging into permissions for GitHub Actions, by default we are given read/write permissions for most scopes: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
However, when we set the `permissions` key, it unsets the rest of the scope to no access:
>When the permissions key is used, all unspecified permissions are set to no access, with the exception of the metadata scope, which always gets read access.
Changesets works with the default permissions and they don't provide a lot of guidance on which scopes they need. The existing scopes (pre-pull request) were part of some speculation in [a GitHub issue](https://github.com/changesets/action/issues/179#issuecomment-1139116421) …
> chore: give write-all permissions for releasing

- .changeset/brown-bags-complain.md
- packages/big-design-patterns/src/components/Header/Header.tsx
- packages/big-design-patterns/src/components/Header/index.ts
- packages/big-design-patterns/src/components/Header/spec.tsx
- packages/big-design-patterns/src/components/Header/styled.tsx
- packages/big-design-patterns/src/components/index.ts
- packages/big-design-patterns/src/index.ts
- packages/docs/package.json
- pnpm-lock.yaml
Adds the `Header` component to `@bigcomerce/big-design-patterns`!
To create consistency in our Headers across the control panel.
Manual testing, but @deini will come through and write the tests.
Code used to test it out:
```tsx
<Header
actions={[
{
text: 'Main action',
variant: 'primary',
iconLeft: <AddIcon />,
},
{
items: [],
toggle: {
text: 'Secondary',
variant: 'secondary',
iconRight: <ArrowDropDownIcon />,
},
},
{
items: [],
toggle: {
text: 'Tertiary',
variant: 'subtle',
iconRight: <ArrowDropDownIcon />,
},
},
]}
backLink={{
text: 'Back link',
href: '#',
onClick: (event) => {
event.preventDefault();
window.alert('Back button clicked');
},
}}
badge={{
variant: 'success',
label: 'Beta',
}}
description={
<Text>
Main description of the page. It provides a comprehensive overview, …
```
> feat(patterns): implement the Header component

- .circleci/config.yml
- package.json
- pnpm-lock.yaml
Updates `pnpm` to the latest version.
Version 9 gets an upgrade to generating it's lockfile. It allows merge conflicts with the package-lock.yml file to be easier to grep.
N/A
See CI runs.
> chore: update pnpm corepack version to latest

- packages/big-design-patterns/README.md
Adds the quick start guide the `@bigcommerce/big-design-patterns` README.
To provide some information on how to start using the components.
N/A
N/A
> docs: add quick start guide to README

- .changeset/cyan-games-pump.md
- README.md
- packages/docs/PropTables/HeaderPropTable.tsx
- packages/docs/components/CodePreview/CodePreview.tsx
- packages/docs/components/PropTable/PropTable.tsx
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/pages/header.tsx
Adding the header pattern component documentation
To guide developers on how to use the header component
> docs: add header pattern documentation

- .changeset/silent-feet-punch.md
- packages/big-design-patterns/src/components/Header/Header.tsx
Remove unused PropsWithChildren type as we don't actually consume `children` within the `Header` component.
N/A
N/A
> fix(patterns): remove unused PropsWithChildren type

- packages/big-design-patterns/src/components/Page/Page.tsx
- packages/big-design-patterns/src/components/Page/styled.tsx
Removes an unused `actionBar` prop that was passed into `StyledPageBackground`.
Unused 🤷 
Changeset not required as `ActionBar` is not released yet.
N/A
N/A
> fix(patterns): remove unused actionBar prop

- .changeset/neat-phones-bow.md
- packages/big-design/src/components/Checkbox/styled.tsx
- packages/big-design/src/components/FileUploader/DropZone.tsx
- packages/big-design/src/components/FileUploader/File.tsx
- packages/big-design/src/components/FileUploader/FileUploader.tsx
- packages/big-design/src/components/FileUploader/styled.ts
- packages/big-design/src/components/Grid/Item/styled.tsx
- packages/big-design/src/components/Radio/Radio.tsx
- packages/big-design/src/components/Radio/styled.tsx
- packages/big-design/src/components/Tree/TreeNode/styled.tsx
- packages/big-design/src/components/Tree/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Worksheet/styled.tsx
Adds `defaultProps` to styled-components so they can be used without wrapping them in a theme provider.
N/A
See CI.
> fix: add default theme to styled components

- .changeset/mighty-brooms-eat.md
- packages/big-design-patterns/src/components/Page/styled.tsx
Fixed the page width css for page to occupy the available width instead of hugging contents
To avoid pages to be shrunk to the center of the screen misaligned with action bar and having a consistent experience
<details>
<summary><code>dev.tsx</code> code</summary>
```tsx
import { Page, Header, ActionBar } from '@bigcommerce/big-design-patterns';
import { Panel, Text } from '@bigcommerce/big-design';
import { AddIcon } from '@bigcommerce/big-design-icons';
const PageWithActionBar = () => {
return (
<Page
actionBar={
<ActionBar
actions={[
{
text: 'Main action',
variant: 'primary',
},
{
text: 'Dismiss',
variant: 'subtle',
},
]}
/>
}
header={
<Header
actions={[
{
text: 'Secondary',
variant: 'secondary',
iconLeft: <AddIcon />,
},
]}
description="Page description (optional)"
title="Page with …
```
> fix(patterns): fix page width to occupy available space

- .changeset/gentle-goats-cheer.md
- packages/big-design-patterns/src/components/Header/Header.tsx
When adding support for iframes #1525, we introduced a bug where the header doesn't wrap correctly. This fixes that issue.
Local testing proof.
> fix(patterns): adjust flex layout for header

- package.json
- packages/big-design-theme/package.json
- pnpm-lock.yaml
- Upgrades `pnpm`
- Removes unused `lerna` dep
- Fixes workspace link
Package link was causing dependabot and installing deps locally to fail.
N/A
Successful install:
> chore: upgrades and cleanup of package.json

- .changeset/sharp-rabbits-end.md
- packages/docs/next.config.js
- packages/examples/.eslintrc.js
- packages/examples/package.json
- packages/examples/src/ProductForm.tsx
- packages/examples/src/index.tsx
- pnpm-lock.yaml
Seems like codesandbox deprecated their old links. This update to the new link following their documentation https://codesandbox.io/docs/learn/devboxes/synced-templates#directly-from-the-github-url
https://codesandbox.io/p/devbox/github/bigcommerce/big-design/tree/fix/codesandbox-link/packages/examples
> fix(docs): fix codesandbox link

- packages/examples/.eslintrc.js
We were accidentally linting node_modules and the dist files causing a long lint task to run. This ignores those folders.
N/A
See CI.
> fix: add eslint ignore to examples repo

- packages/big-design/src/components/PillTabs/PillTabs.tsx
- packages/big-design/src/components/PillTabs/__snapshots__/spec.tsx.snap
Ensure PillTabs use buttons of type button rather than submit
This resolves #1573 so that using PillTabs do not submit any form they are contained by. 
Manually tested by wrapping PillTabs in a form and ensuring it is no longer submitted.
> fix(component): PillTabs no longer submit form

- packages/big-design/src/components/FileUploader/DropZone.tsx
- packages/big-design/src/components/FileUploader/FileUploader.tsx
- packages/big-design/src/components/FileUploader/spec.tsx
- packages/big-design/src/components/FileUploader/types.ts
- packages/docs/PropTables/DropdownPropTable.tsx
- packages/docs/PropTables/FileUploaderPropTable.tsx
- packages/docs/pages/file-uploader.tsx
Add `action` prop to FileUploader.
To be able to pass the custom action for `FileUploader` component.
Locally + UT.
> feat(component): Add action props to FileUploader

- .changeset/tough-melons-trade.md
- packages/big-design-patterns/package.json
When using `workspace:^` as a `peerDependencies` in a package, `changesets` bumps it as a major version every release. This is not ideal in our current workflow.
https://github.com/changesets/changesets/blob/main/docs/decisions.md#the-versioning-of-peer-dependencies
Locks patterns to use `^1.0.0` for big-design et. al packages in `peerDependencies`.
N/A
Have to merge this PR and check the Version PR to see if it works correctly.
> chore(patterns): lock peer deps to v1 of big-design

- .changeset/config.json
- .changeset/tough-melons-trade.md
- packages/big-design-patterns/package.json
Reverts previous PR and adds an experimental option for changeset to only update peer deps when they are out of range. See documentation: https://github.com/changesets/changesets/blob/baf56448606e005577dbe2fb1e78ff457dcaaefd/docs/experimental-options.md?plain=1#L13-L17
N/A
Can only be tested in the version PR.
> chore: only update peer deps when out of range

- .changeset/config.json
- package.json
- patches/@changesets__assemble-release-plan.patch
- pnpm-lock.yaml
Patches @changesets/assemble-release-plan since it causes peer deps to bump to a major version.
N/A
Running `pnpm changeset version` locally:
> chore: patch @changesets/assemble-release-plan

- .changeset/four-toes-rush.md
- .changeset/purple-shirts-promise.md
- packages/big-design/src/components/StatelessPagination/StatelessPagination.tsx
- packages/big-design/src/components/StatelessPagination/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/StatelessPagination/index.ts
- packages/big-design/src/components/StatelessPagination/spec.tsx
- packages/big-design/src/components/StatelessPagination/styled.tsx
- packages/big-design/src/components/index.ts
- packages/docs/PropTables/StatelessPaginationPropTable.tsx
- packages/docs/PropTables/index.ts
- packages/docs/components/SideNav/SideNav.tsx
- packages/docs/pages/stateless-pagination.tsx
- Add new `StatelessPagination` component
- Add new documentation detailing `StatelessPagination`
- `StatelessPagination` will be added as an option for the `Table` component in a seperate, upcoming PR
- `OffsetPagination` will be changed to use `StatelessPagination` under the hood in a seperate, upcoming PR
- The current `OffsetPagination` component is highly stateful and requires knowable page numbers, these concepts are incompatible with cursor-based pagination
- cursor-based pagination has very fluid concepts of 'pages' and how many there might be
- cursor-based pagination `next` and `previous` actions are knowable for the current page only, they cannot be deterministically calculated for _all_ pages ahead of time
- The component's props and internals are completely agnostic to …
> Add new StatelessPagination component and documentation

- .changeset/soft-files-know.md
- packages/big-design/src/components/Table/Actions/Actions.tsx
- packages/big-design/src/components/Table/SelectAll/SelectAll.tsx
- packages/big-design/src/components/Table/Table.tsx
- packages/big-design/src/components/Table/TablePagination/TablePagination.tsx
- packages/big-design/src/components/Table/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Table/discriminatePagination.ts
- packages/big-design/src/components/Table/spec.tsx
- packages/big-design/src/components/Table/types.ts
- packages/big-design/src/components/TableNext/Actions/Actions.tsx
- packages/big-design/src/components/TableNext/SelectAll/SelectAll.tsx
- packages/big-design/src/components/TableNext/TableNext.tsx
- packages/big-design/src/components/TableNext/TablePagination/TablePagination.tsx
- packages/big-design/src/components/TableNext/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/TableNext/discriminatePagination.ts
- packages/big-design/src/components/TableNext/helpers/pagination/index.ts
- packages/big-design/src/components/TableNext/spec.tsx
- packages/big-design/src/components/TableNext/types.ts
- packages/docs/PropTables/TablePropTable.tsx
- packages/docs/next-env.d.ts
- packages/docs/pages/table.tsx
**N.B.**
- best read with `Hide whitespace` enabled as some nesting/spacing has changed
- the duplication across `Table` and `TableNext` is intentional and required
- the long term plan is to eventually move everyone to `TableNext`, duplication prevents entanglement
- Enable our `Table` component to make use of `StatelessPagination`
- Additive change where a `Table`'s pagination prop can be either those of `OffsetPagination` _or_ `StatelessPagination`
- the developer adheres to either signature, which is then discriminated within the `Table` component
- Allows `Table` consumers to make use of cursor-based, or more opinionated, versions of pagination 
https://github.com/user-attachments/assets/2aed49d0-1783-483e-b73c-344f10583f3a
(the examples used in the video were _not_ added to this PR …
> Incorporate StatelessPagination to Table and TableNext

- .changeset/dirty-dolls-beg.md
- packages/big-design-patterns/src/components/Header/Header.tsx
Memoize page header component
When using this component, React Testing Library could not detect when the button is clicked, but fixed after memoizing the component. It might be how final-form being volatile and re-rendering
N/A
Manual testing
ping @bigcommerce/team-customers @leeBigCommerce
> Memoize page header component

- packages/big-design-patterns/package.json
- packages/big-design/package.json
- pnpm-lock.yaml
Removes `react-test-renderer`.
It's deprecated in version 19+ plus we don't use it as a peer dependency anymore. It was primarily used in `@testing-library/react-hooks` but that package is deprecated too.
N/A
See CI for test suite run.
Closes #1605
> chore: remove react-test-renderer

- .changeset/five-monkeys-provide.md
- packages/big-design/src/components/StatefulTree/spec.tsx
- packages/big-design/src/components/Tree/TreeNode/TreeNode.tsx
- packages/big-design/src/components/Tree/__snapshots__/spec.tsx.snap
- packages/big-design/src/components/Tree/spec.tsx
- packages/big-design/src/components/Tree/styled.ts
- Add `conditional rendering` for the `TreeNode` instead of display: none to improve initial rendering performance;
- Regenerate snapshots
- Fix `Tree` tests according to the new changes.
Browser can't handle big tree structure on initial rendering.
No UI changes.
Existing tests + updated tests.
> fix(component): add conditional rendering for tree component
